import { useLocale } from "./locale";
import { PRODUCT_LOCALES } from "./product";

// Same locale order as the existing product and service-scope catalogs.
const TEXT = {
  add: ["Add device", "添加设备", "Gerät hinzufügen", "Ajouter un appareil", "デバイスを追加", "기기 추가", "新增裝置"],
  intro: ["Connect another machine’s Runner to this Server. Its projects stay on that machine.", "将其他机器的 Runner 接入此 Server。项目文件保留在各自机器上。", "Den Runner eines weiteren Rechners mit diesem Server verbinden. Projekte bleiben auf diesem Rechner.", "Connectez le Runner d’une autre machine à ce Server. Ses projets restent sur cette machine.", "別のマシンの Runner をこの Server に接続します。プロジェクトは各マシンに保存されます。", "다른 컴퓨터의 Runner를 이 Server에 연결합니다. 프로젝트는 각 컴퓨터에 유지됩니다.", "將其他機器的 Runner 接入此 Server。專案檔案保留在各自機器上。"],
  address: ["Server URL for the other machine", "其他机器可访问的 Server 地址", "Server-URL für den anderen Rechner", "URL du Server accessible à l’autre machine", "別のマシンからアクセスできる Server URL", "다른 컴퓨터에서 접근 가능한 Server URL", "其他機器可存取的 Server 位址"],
  network: ["Runner connects directly to this Server URL. ChatGPT uses the separate OpenAI Tunnel connection. Check the listener, firewall, DNS or private network if the URL is unreachable; this dialog does not change them.", "Runner 直接连接此 Server 地址；ChatGPT 使用独立的 OpenAI Tunnel 连接。无法访问时，请检查监听地址、防火墙、域名或私有网络；此窗口不会修改这些设置。", "Runner verbindet sich direkt mit dieser URL. ChatGPT nutzt die separate OpenAI-Tunnel-Verbindung. Bei Verbindungsproblemen Listener, Firewall, DNS oder privates Netzwerk prüfen; dieser Dialog ändert sie nicht.", "Le Runner se connecte directement à cette URL. ChatGPT utilise la connexion OpenAI Tunnel séparée. Vérifiez l’écoute, le pare-feu, le DNS ou le réseau privé si l’URL est inaccessible ; ce dialogue ne les modifie pas.", "Runner はこの URL に直接接続し、ChatGPT は別の OpenAI Tunnel 接続を使用します。接続できない場合はリスナー、ファイアウォール、DNS、プライベートネットワークを確認してください。この画面では変更しません。", "Runner는 이 URL에 직접 연결하고 ChatGPT는 별도의 OpenAI Tunnel 연결을 사용합니다. 접근할 수 없으면 수신 주소, 방화벽, DNS 또는 사설망을 확인하세요. 이 창은 해당 설정을 변경하지 않습니다.", "Runner 直接連線此 Server 位址；ChatGPT 使用獨立的 OpenAI Tunnel 連線。無法存取時，請檢查監聽位址、防火牆、網域或私有網路；此視窗不會修改這些設定。"],
  invalid: ["Enter an HTTP or HTTPS Server origin, without a path, credentials, query or fragment.", "请输入 HTTP 或 HTTPS Server 地址，不含路径、凭据、查询参数或片段。", "HTTP- oder HTTPS-Server-Adresse ohne Pfad, Zugangsdaten, Abfrage oder Fragment eingeben.", "Saisissez une origine HTTP ou HTTPS sans chemin, identifiants, paramètres ni fragment.", "パス、認証情報、クエリ、フラグメントを含まない HTTP または HTTPS の Server URL を入力してください。", "경로, 자격 증명, 쿼리 또는 프래그먼트 없는 HTTP 또는 HTTPS Server 주소를 입력하세요.", "請輸入 HTTP 或 HTTPS Server 位址，不含路徑、憑據、查詢參數或片段。"],
  loopback: ["Loopback and wildcard addresses are not an address for another machine. Use this Server’s reachable hostname or network address.", "环回地址和通配监听地址不能用于其他机器接入。请提供此 Server 可达的域名或网络地址。", "Loopback- und Platzhalteradressen sind für andere Rechner ungeeignet. Einen erreichbaren Hostnamen oder eine Netzwerkadresse dieses Servers verwenden.", "Les adresses locales et génériques ne conviennent pas à une autre machine. Utilisez un nom d’hôte ou une adresse réseau accessible de ce Server.", "ループバックやワイルドカードは別のマシンの接続先にできません。この Server のアクセス可能なホスト名またはネットワークアドレスを使用してください。", "루프백 및 와일드카드 주소는 다른 컴퓨터의 접속 주소가 될 수 없습니다. 접근 가능한 이 Server의 호스트 이름 또는 네트워크 주소를 사용하세요.", "環回位址和萬用監聽位址不能用於其他機器接入。請提供此 Server 可達的網域或網路位址。"],
  openai: ["An OpenAI or ChatGPT address is not a Runner endpoint. Use the direct URL of your central Server.", "OpenAI 或 ChatGPT 地址不是 Runner 接入口。请使用中心 Server 的直接地址。", "Eine OpenAI- oder ChatGPT-Adresse ist kein Runner-Endpunkt. Die direkte URL des zentralen Servers verwenden.", "Une adresse OpenAI ou ChatGPT n’est pas un point d’accès Runner. Utilisez l’URL directe de votre Server central.", "OpenAI や ChatGPT のアドレスは Runner の接続先ではありません。中央 Server の直接 URL を使用してください。", "OpenAI 또는 ChatGPT 주소는 Runner 접속 주소가 아닙니다. 중앙 Server의 직접 URL을 사용하세요.", "OpenAI 或 ChatGPT 位址不是 Runner 接入口。請使用中心 Server 的直接位址。"],
  create: ["Create invitation", "创建邀请", "Einladung erstellen", "Créer une invitation", "招待を作成", "초대 만들기", "建立邀請"],
  idle: ["No invitation created", "尚未创建邀请", "Noch keine Einladung erstellt", "Aucune invitation créée", "招待は未作成です", "초대가 아직 없습니다", "尚未建立邀請"],
  creating: ["Creating invitation…", "正在创建邀请…", "Einladung wird erstellt…", "Création de l’invitation…", "招待を作成中…", "초대 생성 중…", "正在建立邀請…"],
  created: ["Invitation created · device connection not yet confirmed", "邀请已创建 · 尚未确认设备接入", "Einladung erstellt · Geräteverbindung noch nicht bestätigt", "Invitation créée · connexion de l’appareil non confirmée", "招待を作成しました · デバイス接続は未確認です", "초대 생성됨 · 기기 연결은 아직 확인되지 않음", "邀請已建立 · 尚未確認裝置接入"],
  code: ["One-time pairing code", "一次性配对码", "Einmaliger Kopplungscode", "Code d’appairage à usage unique", "ワンタイムペアリングコード", "일회용 페어링 코드", "一次性配對碼"],
  validity: ["Valid for ten minutes and one use. Closing this dialog clears its copy here, not the Server invitation. Reopening does not create a new code.", "有效期十分钟，仅可使用一次。关闭窗口会清除这里的配对码，但不会撤销 Server 上的邀请。重新打开不会生成新码。", "Zehn Minuten gültig, einmal verwendbar. Schließen entfernt nur die lokale Kopie, nicht die Server-Einladung. Erneutes Öffnen erzeugt keinen Code.", "Valable dix minutes et une seule fois. Fermer efface la copie locale, sans révoquer l’invitation du Server. Rouvrir ne crée aucun code.", "有効期間は10分で、1回のみ使用できます。閉じるとここに表示したコードを消去しますが、Server 上の招待は取り消しません。再度開いても新規作成しません。", "10분 동안 한 번만 사용할 수 있습니다. 창을 닫으면 여기의 코드가 지워지지만 Server 초대는 취소되지 않습니다. 다시 열어도 새 코드를 생성하지 않습니다.", "有效期十分鐘，僅可使用一次。關閉視窗會清除這裡的配對碼，但不會撤銷 Server 上的邀請。重新開啟不會產生新碼。"],
  show: ["Show code", "查看配对码", "Code anzeigen", "Afficher le code", "コードを表示", "코드 보기", "查看配對碼"],
  hide: ["Hide code", "隐藏配对码", "Code ausblenden", "Masquer le code", "コードを隠す", "코드 숨기기", "隱藏配對碼"],
  copyCode: ["Copy pairing code", "复制配对码", "Kopplungscode kopieren", "Copier le code", "ペアリングコードをコピー", "페어링 코드 복사", "複製配對碼"],
  copyAddress: ["Copy Server URL", "复制 Server 地址", "Server-URL kopieren", "Copier l’URL du Server", "Server URL をコピー", "Server URL 복사", "複製 Server 位址"],
  copied: ["Copied", "已复制", "Kopiert", "Copié", "コピーしました", "복사됨", "已複製"],
  copyFailed: ["Copy failed. Use the explicit Show code action to read it.", "复制失败。可点击“查看配对码”读取。", "Kopieren fehlgeschlagen. Den Code mit „Code anzeigen“ lesen.", "Échec de la copie. Utilisez « Afficher le code » pour le lire.", "コピーに失敗しました。「コードを表示」で確認してください。", "복사에 실패했습니다. ‘코드 보기’를 눌러 확인하세요.", "複製失敗。可點選「查看配對碼」讀取。"],
  expired: ["The local display period ended. Check the device list before explicitly creating another invitation.", "本地展示有效期已结束。请先检查设备列表，再明确创建另一份邀请。", "Die lokale Anzeigezeit ist abgelaufen. Vor einer neuen Einladung zuerst die Geräteliste prüfen.", "La période d’affichage locale est terminée. Vérifiez les appareils avant de créer explicitement une autre invitation.", "ローカルの表示期間が終了しました。別の招待を明示的に作成する前にデバイス一覧を確認してください。", "로컬 표시 기간이 끝났습니다. 다른 초대를 직접 만들기 전에 기기 목록을 확인하세요.", "本地展示有效期已結束。請先檢查裝置清單，再明確建立另一份邀請。"],
  denied: ["The Server did not authorize this invitation. Check the saved environment’s access; no service settings were changed.", "Server 未授权此次邀请。请检查已保存环境的访问权限；服务设置未修改。", "Der Server hat die Einladung nicht autorisiert. Zugriff der gespeicherten Umgebung prüfen; Diensteinstellungen wurden nicht geändert.", "Le Server n’a pas autorisé l’invitation. Vérifiez l’accès de l’environnement enregistré ; aucun réglage de service n’a changé.", "Server が招待を許可しませんでした。保存済み環境の権限を確認してください。サービス設定は変更していません。", "Server가 초대를 허용하지 않았습니다. 저장된 환경의 접근 권한을 확인하세요. 서비스 설정은 변경되지 않았습니다.", "Server 未授權此次邀請。請檢查已儲存環境的存取權限；服務設定未修改。"],
  failed: ["Invitation request failed or its result is unconfirmed. Check this Server and the device list before explicitly trying again. No new code is requested automatically.", "邀请请求失败或结果未确认。请检查此 Server 和设备列表，再决定是否重试。不会自动请求新码。", "Einladungsanfrage fehlgeschlagen oder Ergebnis unbestätigt. Server und Geräteliste vor einem erneuten Versuch prüfen. Kein Code wird automatisch angefordert.", "Demande échouée ou résultat non confirmé. Vérifiez ce Server et les appareils avant de réessayer. Aucun code n’est demandé automatiquement.", "招待要求が失敗したか、結果を確認できません。再試行前に Server とデバイス一覧を確認してください。新しいコードは自動要求しません。", "초대 요청이 실패했거나 결과가 확인되지 않았습니다. 다시 시도하기 전에 이 Server와 기기 목록을 확인하세요. 새 코드를 자동 요청하지 않습니다.", "邀請請求失敗或結果未確認。請檢查此 Server 和裝置清單，再決定是否重試。不會自動請求新碼。"],
  install: ["On the other machine, install WebCodex for its OS and architecture. Open First Run and choose Join main node.", "在其他机器安装适配系统和架构的 WebCodex，打开首次设置，选择“加入主节点”。", "Auf dem anderen Rechner WebCodex passend zu System und Architektur installieren. Bei der Ersteinrichtung „Hauptknoten beitreten“ wählen.", "Sur l’autre machine, installez WebCodex adapté au système et à l’architecture. À la première configuration, choisissez « Rejoindre le nœud principal ».", "別のマシンに OS とアーキテクチャに適した WebCodex をインストールし、初回設定で「メインノードに参加」を選択します。", "다른 컴퓨터에 OS와 아키텍처에 맞는 WebCodex를 설치하고 첫 설정에서 ‘주 노드에 참여’를 선택하세요.", "在其他機器安裝適配系統和架構的 WebCodex，開啟首次設定，選擇「加入主節點」。"],
  join: ["Enter this reachable Server URL and pairing code in the protected input. A local Runner is enabled; initial project selection is optional. No Tunnel key or Server bootstrap credential is needed.", "输入可达的 Server 地址，通过受保护输入填写配对码。本机 Runner 默认启用，初始项目可跳过。无需 Tunnel Key 或 Server bootstrap 凭据。", "Erreichbare Server-URL und Code im geschützten Feld eingeben. Lokaler Runner ist aktiviert; erstes Projekt optional. Keine Tunnel- oder Server-Bootstrap-Zugangsdaten nötig.", "Saisissez l’URL accessible et le code dans le champ protégé. Le Runner local est activé ; le projet initial est facultatif. Aucun identifiant Tunnel ou bootstrap Server nécessaire.", "アクセス可能な Server URL とコードを保護された入力欄に入力します。ローカル Runner は有効で、初期プロジェクトは省略できます。Tunnel キーや Server の bootstrap 情報は不要です。", "접근 가능한 Server URL과 코드를 보호된 입력란에 입력하세요. 로컬 Runner가 활성화되며 초기 프로젝트는 선택 사항입니다. Tunnel 키나 Server bootstrap 자격 증명은 필요하지 않습니다.", "輸入可達的 Server 位址，透過受保護輸入填寫配對碼。本機 Runner 預設啟用，初始專案可跳過。無需 Tunnel Key 或 Server bootstrap 憑據。"],
  verify: ["Refresh Devices and Projects after joining. An invitation alone does not confirm a Runner connection or a successful ChatGPT project read.", "加入后刷新设备和项目列表。创建邀请不代表 Runner 已接入，也不代表 ChatGPT 已成功读取项目。", "Nach dem Beitritt Geräte und Projekte aktualisieren. Eine Einladung bestätigt weder Runner-Verbindung noch erfolgreichen ChatGPT-Projektzugriff.", "Actualisez les appareils et projets après l’ajout. Une invitation seule ne confirme ni la connexion Runner ni une lecture de projet réussie par ChatGPT.", "参加後にデバイスとプロジェクトを更新してください。招待だけでは Runner 接続や ChatGPT によるプロジェクト読み取り成功を確認できません。", "참여 후 기기와 프로젝트를 새로 고침하세요. 초대만으로는 Runner 연결이나 ChatGPT의 프로젝트 읽기 성공이 확인되지 않습니다.", "加入後重新整理裝置和專案清單。建立邀請不代表 Runner 已接入，也不代表 ChatGPT 已成功讀取專案。"],
  devices: ["View devices and projects", "查看设备和项目", "Geräte und Projekte anzeigen", "Voir les appareils et projets", "デバイスとプロジェクトを表示", "기기 및 프로젝트 보기", "查看裝置和專案"],
  close: ["Close", "关闭", "Schließen", "Fermer", "閉じる", "닫기", "關閉"],
} as const satisfies Record<string, readonly [string, string, string, string, string, string, string]>;

export function deviceInvitationText(locale: string, key: keyof typeof TEXT): string {
  const index = PRODUCT_LOCALES.indexOf(locale as typeof PRODUCT_LOCALES[number]);
  return TEXT[key][index < 0 ? 0 : index];
}
export function useDeviceInvitationText() {
  const { locale } = useLocale();
  return (key: keyof typeof TEXT) => deviceInvitationText(locale, key);
}
