import { useLocale } from "./locale";
import { PRODUCT_LOCALES } from "./product";

// English, Chinese, German, French, Japanese, Korean. Accessible automation
// names on critical controls stay stable independently of the selected locale.
export const RUNNER_CAPABILITIES_MESSAGES = {
  authorizationNeeded: ["This connection needs permission to use this Runner capability. Authorize locally before delegating work.", "当前连接尚未获得此 Runner 能力的使用权限。请先进行本地授权。", "Dieser Verbindung fehlt die Berechtigung. Vor der Nutzung lokal autorisieren.", "Cette connexion nécessite une autorisation locale avant utilisation.", "この接続には使用権限が必要です。先にローカルで許可してください。", "이 연결에는 사용 권한이 필요합니다. 먼저 로컬 승인을 진행하세요.", "當前連線尚未獲得此 Runner 能力的使用權限。請先進行本機授權。"],
  authorizationUnavailable: ["Runner authorization could not be observed. Refresh to check current access.", "暂时无法读取 Runner 授权状态，请刷新确认当前权限。", "Runner-Berechtigungen nicht verfügbar. Zugriff aktualisieren.", "Impossible de vérifier l’autorisation. Actualisez pour vérifier l’accès.", "権限を確認できません。更新して再確認してください。", "권한을 확인하지 못했습니다. 새로 고침하여 확인하세요.", "暫時無法讀取 Runner 授權狀態，請重新整理確認當前權限。"],
  operatorPairingNeeded: ["Ask the Server operator for a pairing code with Runner capability access. Remote access cannot be granted locally.", "请使用 Server 操作者授予了 Runner 能力的配对码。远程连接不能在本地提权。", "Kopplungscode mit Runner-Berechtigungen beim Server-Operator anfordern. Kein lokaler Grant für Remote-Verbindungen.", "Demandez à l’opérateur un code avec les droits Runner. Aucun droit distant n’est accordé localement.", "Runner 権限付きコードを管理者に依頼してください。リモート接続にはローカルで権限を付与できません。", "서버 운영자에게 Runner 권한이 있는 페어링 코드를 요청하세요. 원격 권한은 로컬에서 부여할 수 없습니다.", "請使用 Server 操作者授予了 Runner 能力的配對碼。遠端連線不能在本機提權。"],
  authorize: ["Authorize Runner Capabilities", "授权 Runner 能力", "Runner-Funktionen autorisieren", "Autoriser les fonctions Runner", "Runner 機能を許可", "Runner 기능 승인", "授權 Runner 能力"],
  authorizeHelp: ["Allow this Desktop connection to manage SSH Resources and delegate work to configured Coding Agents. This uses the local Server operator's authority. Existing tokens, expiry, Runner, Server and Tunnel processes are unchanged.", "允许此 Desktop 连接管理 SSH 资源并委托已配置的编程代理。这将使用本地 Server 操作者权限；现有令牌、有效期及 Runner、Server、Tunnel 进程保持不变。", "Dieser Desktop-Verbindung SSH-Verwaltung und Delegation an konfigurierte Agenten erlauben. Verwendet lokale Server-Operatorrechte. Token, Ablauf und Prozesse bleiben unverändert.", "Autoriser cette connexion à gérer SSH et à déléguer aux agents configurés, avec l’autorité de l’opérateur local. Jetons, expiration et processus restent inchangés.", "この接続に SSH 管理と設定済みエージェントへの委任を許可します。ローカル Server の管理権限を使用します。トークン、有効期限、プロセスは変更しません。", "로컬 서버 운영자 권한으로 이 연결의 SSH 관리와 설정된 에이전트 위임을 승인합니다. 기존 토큰, 만료 시간 및 프로세스는 변경하지 않습니다.", "允許此 Desktop 連線管理 SSH 資源並委託已設定的程式代理。這將使用本機 Server 操作者權限；現有令牌、有效期及 Runner、Server、Tunnel 程序保持不變。"],
  authorizeFailed: ["Authorization was not confirmed. Refresh to observe current access; no automatic retry was made.", "尚未确认授权结果。请刷新以观察当前权限；未自动重试。", "Autorisierung nicht bestätigt. Aktuellen Zugriff aktualisieren; keine automatische Wiederholung.", "Autorisation non confirmée. Actualisez pour vérifier l’accès ; aucun essai automatique.", "許可結果を確認できませんでした。更新して現在の権限を確認してください。自動再試行は行っていません。", "승인 결과를 확인하지 못했습니다. 새로 고침하여 현재 권한을 확인하세요. 자동 재시도는 하지 않았습니다.", "尚未確認授權結果。請重新整理以觀察當前權限；未自動重試。"],
  codingAgents: ["Coding Agents", "编程代理", "Programmieragenten", "Agents de code", "コーディングエージェント", "코딩 에이전트", "程式代理"],
  sshResources: ["SSH Resources", "SSH 资源", "SSH-Ressourcen", "Ressources SSH", "SSH リソース", "SSH 리소스", "SSH 資源"],
  addCodingAgent: ["Add Coding Agent", "添加编程代理", "Programmieragent hinzufügen", "Ajouter un agent de code", "エージェントを追加", "코딩 에이전트 추가", "新增程式代理"],
  addSshResource: ["Add SSH Resource", "添加 SSH 资源", "SSH-Ressource hinzufügen", "Ajouter une ressource SSH", "SSH リソースを追加", "SSH 리소스 추가", "新增 SSH 資源"],
  providerId: ["Provider ID", "Provider ID", "Anbieter-ID", "ID du fournisseur", "プロバイダー ID", "공급자 ID", "Provider ID"],
  executable: ["Executable", "可执行文件", "Programmdatei", "Exécutable", "実行ファイル", "실행 파일", "可執行檔案"],
  active: ["Active", "已生效", "Aktiv", "Actif", "有効", "활성", "已生效"],
  restartRequired: ["Restart required", "需要重启", "Neustart erforderlich", "Redémarrage requis", "再起動が必要", "다시 시작 필요", "需要重啟"],
  savedRestart: ["Saved · Restart Runner to apply", "已保存 · 重启 Runner 后生效", "Gespeichert · Runner zum Anwenden neu starten", "Enregistré · Redémarrez Runner pour appliquer", "保存済み · Runner を再起動して適用", "저장됨 · 적용하려면 Runner 다시 시작", "已儲存 · 重啟 Runner 後生效"],
  observed: ["Currently advertised by Runner", "Runner 当前实际通告", "Aktuell vom Runner gemeldet", "Actuellement annoncé par Runner", "Runner が現在公開中", "Runner가 현재 알림", "Runner 當前實際通告"],
  readOnly: ["Read only", "只读", "Schreibgeschützt", "Lecture seule", "読み取り専用", "읽기 전용", "只讀"],
  noCodingAgents: ["No Coding Agents configured", "尚未配置编程代理", "Keine Programmieragenten konfiguriert", "Aucun agent configuré", "エージェントは未設定です", "설정된 코딩 에이전트 없음", "尚未設定程式代理"],
  agentHelp: ["Use installed ACP coding tools. Save, then restart Runner to apply.", "让 AI 使用已安装的 ACP 编程工具，保存后重启 Runner 生效。", "Installierte ACP-Werkzeuge nutzen. Speichern und Runner neu starten.", "Utilisez les outils ACP installés. Enregistrez puis redémarrez Runner.", "インストール済み ACP ツールを使います。保存後に Runner を再起動してください。", "설치된 ACP 코딩 도구를 사용합니다. 저장 후 Runner를 다시 시작하세요.", "讓 AI 使用已安裝的 ACP 程式工具，儲存後重新啟動 Runner 生效。"],
  agentArgsHelp: ["JSON array of literal arguments, for example [\"--acp\"]. Do not put credentials here; map environment variable names in Advanced.", "参数为 JSON 数组，例如 [\"--acp\"]。不要在此填写凭据；请在高级设置中映射环境变量名称。", "JSON-Array mit Argumenten, z. B. [\"--acp\"]. Keine Zugangsdaten; Umgebungsnamen unter Erweitert zuordnen.", "Tableau JSON d’arguments, par exemple [\"--acp\"]. Aucun identifiant ; associez les noms de variables dans Avancé.", "引数を JSON 配列で指定します（例：[\"--acp\"]）。認証情報ではなく、詳細設定で環境変数名を対応付けます。", "인수의 JSON 배열입니다(예: [\"--acp\"]). 자격 증명은 입력하지 말고 고급 설정에서 환경 변수 이름을 매핑하세요.", "引數為 JSON 陣列，例如 [\"--acp\"]。不要在此填寫憑據；請在高階設定中對映環境變數名稱。"],
  envMapping: ["Environment name mapping", "环境变量名称映射", "Zuordnung von Umgebungsnamen", "Association des noms de variables", "環境変数名の対応付け", "환경 변수 이름 매핑", "環境變數名稱對映"],
  envHelp: ["Names only: child variable ← Runner variable. Secret values remain in the operator environment or private agent configuration and are never read here.", "只填写名称：子进程变量 ← Runner 变量。密钥值保留在操作者环境或代理私密配置中，此处不会读取。", "Nur Namen: Kindvariable ← Runner-Variable. Geheime Werte bleiben privat und werden hier nie gelesen.", "Noms uniquement : variable enfant ← variable Runner. Les valeurs secrètes restent privées et ne sont jamais lues ici.", "名前のみ：子プロセス変数 ← Runner 変数。秘密値は環境または非公開設定に保持され、ここでは読み取りません。", "이름만 입력: 자식 변수 ← Runner 변수. 비밀 값은 운영자 환경 또는 비공개 설정에 유지되며 여기서는 읽지 않습니다.", "只填寫名稱：子程序變數 ← Runner 變數。金鑰值保留在操作者環境或代理私密設定中，此處不會讀取。"],
  childVariable: ["Child variable", "子进程变量名", "Kindvariable", "Variable enfant", "子プロセス変数", "자식 변수", "子程序變數名"],
  runnerVariable: ["Runner variable", "Runner 变量名", "Runner-Variable", "Variable Runner", "Runner 変数", "Runner 변수", "Runner 變數名"],
  addMapping: ["Add Environment Mapping", "添加变量映射", "Umgebungszuordnung hinzufügen", "Ajouter une association", "環境変数の対応を追加", "환경 변수 매핑 추가", "新增變數對映"],
  allowedOptions: ["Allowed config options (JSON array)", "允许的配置选项（JSON 数组）", "Erlaubte Optionen (JSON-Array)", "Options autorisées (tableau JSON)", "許可する設定項目（JSON 配列）", "허용된 설정 옵션(JSON 배열)", "允許的設定選項（JSON 陣列）"],
  globalSettings: ["Manage global ACP settings", "管理全局 ACP 设置", "Globale ACP-Einstellungen verwalten", "Gérer les paramètres ACP globaux", "ACP 全体の設定を管理", "전역 ACP 설정 관리", "管理全域 ACP 設定"],
  preserveGlobals: ["When unchecked, existing Runner global settings are left unchanged.", "不勾选时，保留 Runner 现有全局设置。", "Ohne Auswahl bleiben globale Einstellungen unverändert.", "Sans sélection, les paramètres globaux restent inchangés.", "未選択の場合、現在の全体設定を保持します。", "선택하지 않으면 기존 전역 설정을 유지합니다.", "不勾選時，保留 Runner 現有全域設定。"],
  maxConcurrent: ["Max concurrent runs", "最大并发运行数", "Maximale parallele Läufe", "Exécutions simultanées max.", "最大同時実行数", "최대 동시 실행 수", "最大併發執行數"],
  permissionTimeout: ["Permission timeout (seconds)", "权限响应超时（秒）", "Berechtigungsfrist (Sekunden)", "Délai d’autorisation (secondes)", "権限応答の制限時間（秒）", "권한 응답 제한 시간(초)", "權限響應超時（秒）"],
  ownershipConflict: ["This Provider ID is already owned by another configuration. Choose another ID; nothing was overwritten.", "此 Provider ID 已由其他配置拥有。请选择其他 ID；未覆盖任何配置。", "Diese Anbieter-ID gehört einer anderen Konfiguration. Andere ID wählen; nichts wurde überschrieben.", "Cet ID appartient à une autre configuration. Choisissez-en un autre ; rien n’a été écrasé.", "この ID は別の設定が所有しています。別の ID を指定してください。上書きは行っていません。", "이 ID는 다른 설정에서 소유합니다. 다른 ID를 선택하세요. 덮어쓴 내용은 없습니다.", "此 Provider ID 已由其他設定擁有。請選擇其他 ID；未覆蓋任何設定。"],
  removeAgentHelp: ["Remove this Desktop-managed provider from desired state. It may remain active until Runner is restarted. Operator providers are not changed.", "从 Desktop 期望配置中移除此代理。重启 Runner 前它可能仍在运行，不影响操作者手工配置的代理。", "Diesen Desktop-Anbieter entfernen. Er kann bis zum Runner-Neustart aktiv bleiben. Operator-Anbieter bleiben unverändert.", "Retirer cet agent géré par Desktop. Il peut rester actif jusqu’au redémarrage de Runner. Les autres agents restent inchangés.", "Desktop 管理の設定から削除します。Runner の再起動までは有効な場合があります。手動設定は変更しません。", "Desktop 관리 설정에서 제거합니다. Runner를 다시 시작하기 전까지 활성일 수 있습니다. 운영자 설정은 변경하지 않습니다.", "從 Desktop 期望設定中移除此代理。重啟 Runner 前它可能仍在執行，不影響操作者手工設定的代理。"],
  resourceName: ["Resource Name", "资源名称", "Ressourcenname", "Nom de ressource", "リソース名", "리소스 이름", "資源名稱"],
  target: ["Target", "目标", "Ziel", "Cible", "接続先", "대상", "目標"],
  defaultCwd: ["Default Working Directory", "默认工作目录", "Standard-Arbeitsverzeichnis", "Répertoire de travail par défaut", "既定の作業ディレクトリ", "기본 작업 디렉터리", "預設工作目錄"],
  targetHelp: ["Use user@host, a hostname, or an existing OpenSSH alias such as special. SSH resolves the alias; no SSH config or keys are imported.", "可填写 user@host、主机名或已有 OpenSSH 别名，例如 special。别名由 SSH 解析，不导入 SSH 配置或密钥。", "user@host, Hostname oder vorhandenen OpenSSH-Alias wie special verwenden. Keine Konfiguration oder Schlüssel werden importiert.", "Utilisez user@host, un hôte ou un alias OpenSSH existant, comme special. Aucune configuration ni clé n’est importée.", "user@host、ホスト名、既存の OpenSSH エイリアス（例：special）を指定します。設定や鍵はインポートしません。", "user@host, 호스트 이름 또는 special 같은 기존 OpenSSH 별칭을 사용하세요. 설정이나 키를 가져오지 않습니다.", "可填寫 user@host、主機名或已有 OpenSSH 別名，例如 special。別名由 SSH 解析，不匯入 SSH 設定或金鑰。"],
  managed: ["Managed by WebCodex", "由 WebCodex 管理", "Von WebCodex verwaltet", "Gérée par WebCodex", "WebCodex が管理", "WebCodex에서 관리", "由 WebCodex 管理"],
  static: ["From config file", "来自配置文件", "Aus Konfigurationsdatei", "Depuis un fichier de configuration", "設定ファイルから", "설정 파일에서 제공", "來自設定檔"],
  noResources: ["No SSH Resources registered", "尚未注册 SSH 资源", "Keine SSH-Ressourcen registriert", "Aucune ressource SSH enregistrée", "SSH リソースは未登録です", "등록된 SSH 리소스 없음", "尚未註冊 SSH 資源"],
  sshPrivacy: ["Only resource names and status are listed. To change a target, remove the WebCodex-managed resource and add it again. Resources from config files are read only here.", "列表只显示名称和状态。修改目标需移除 WebCodex 管理的资源后重新添加；来自配置文件的资源在此只读。", "Nur Namen und Status werden angezeigt. Zum Ändern eine von WebCodex verwaltete Ressource entfernen und neu hinzufügen. Ressourcen aus Konfigurationsdateien sind hier schreibgeschützt.", "Seuls les noms et états sont affichés. Pour modifier une cible gérée par WebCodex, retirez-la puis ajoutez-la. Les ressources des fichiers de configuration sont en lecture seule ici.", "名前と状態のみ表示します。接続先の変更は WebCodex 管理のリソースを削除して再追加してください。設定ファイルのリソースはここでは読み取り専用です。", "이름과 상태만 표시합니다. 대상을 바꾸려면 WebCodex 관리 리소스를 제거하고 다시 추가하세요. 설정 파일의 리소스는 여기서 읽기 전용입니다.", "清單只顯示名稱和狀態。修改目標需移除 WebCodex 管理的資源後重新新增；來自設定檔的資源在此只讀。"],
  removeResourceHelp: ["Remove this managed SSH reference. This does not delete anything on the remote host or change your OpenSSH configuration.", "移除此托管 SSH 引用，不会删除远程主机上的内容，也不会修改 OpenSSH 配置。", "Diese verwaltete SSH-Referenz entfernen. Remote-Dateien und OpenSSH-Konfiguration bleiben unverändert.", "Retirer cette référence SSH. Rien n’est supprimé sur l’hôte distant et la configuration OpenSSH reste inchangée.", "管理された SSH 参照を削除します。接続先のデータや OpenSSH 設定は変更しません。", "관리 SSH 참조를 제거합니다. 원격 호스트 데이터나 OpenSSH 설정은 변경하지 않습니다.", "移除此託管 SSH 引用，不會刪除遠端主機上的內容，也不會修改 OpenSSH 設定。"],
  uncertain: ["Operation status uncertain. Refresh resources before retrying. The operation will not be retried automatically.", "操作状态不确定。重试前请刷新资源；系统不会自动重试此操作。", "Status ungewiss. Vor erneutem Versuch Ressourcen aktualisieren. Keine automatische Wiederholung.", "État de l’opération incertain. Actualisez avant de réessayer. Aucun nouvel essai automatique.", "操作結果が不明です。再試行前に更新してください。操作は自動再試行されません。", "작업 상태가 불확실합니다. 다시 시도하기 전에 새로 고침하세요. 작업은 자동 재시도되지 않습니다.", "操作狀態不確定。重試前請重新整理資源；系統不會自動重試此操作。"],
  refreshNeeded: ["Runner or resources changed. The list has been refreshed; review it before trying again.", "Runner 或资源已变化。已重新读取列表，请核对后再操作。", "Runner oder Ressourcen geändert. Aktualisierte Liste vor erneutem Versuch prüfen.", "Runner ou les ressources ont changé. Vérifiez la liste actualisée avant de réessayer.", "Runner またはリソースが変更されました。更新した一覧を確認してから再操作してください。", "Runner 또는 리소스가 변경되었습니다. 새 목록을 확인한 후 다시 시도하세요.", "Runner 或資源已變化。已重新讀取清單，請核對後再操作。"],
  nameConflict: ["This resource name is already in use. Choose another name or remove the existing managed resource first.", "资源名称已被占用。请选择其他名称，或先移除已有托管资源。", "Name bereits vergeben. Anderen Namen wählen oder verwaltete Ressource zuerst entfernen.", "Ce nom est déjà utilisé. Choisissez un autre nom ou retirez d’abord la ressource gérée.", "名前は使用中です。別の名前を指定するか、既存の管理対象を先に削除してください。", "이름이 이미 사용 중입니다. 다른 이름을 선택하거나 기존 관리 리소스를 먼저 제거하세요.", "資源名稱已被佔用。請選擇其他名稱，或先移除已有託管資源。"],
  sshUnavailable: ["SSH Resources are unavailable. Check that this Runner is online and supports managed SSH resources.", "SSH 资源暂不可用，请检查此 Runner 是否在线并支持托管 SSH 资源。", "SSH-Ressourcen nicht verfügbar. Online-Status und Runner-Unterstützung prüfen.", "Ressources SSH indisponibles. Vérifiez que Runner est en ligne et prend en charge cette fonction.", "SSH リソースを利用できません。Runner の接続状態と対応状況を確認してください。", "SSH 리소스를 사용할 수 없습니다. Runner 연결 및 지원 여부를 확인하세요.", "SSH 資源暫不可用，請檢查此 Runner 是否線上並支援託管 SSH 資源。"],
  permissionNeeded: ["This connection is not authorized to manage SSH Resources. Use a pairing code with Runner capability access from the Server operator.", "当前连接未获准管理 SSH 资源。请使用 Server 操作者授权了 Runner 能力的配对码。", "Diese Verbindung darf SSH-Ressourcen nicht verwalten. Einen vom Server-Operator freigegebenen Kopplungscode verwenden.", "Cette connexion ne peut pas gérer les ressources SSH. Utilisez un code autorisé par l’opérateur du serveur.", "この接続には SSH リソース管理権限がありません。Server 管理者が権限を付与したペアリングコードを使用してください。", "이 연결에는 SSH 리소스 관리 권한이 없습니다. 서버 운영자가 권한을 부여한 페어링 코드를 사용하세요.", "當前連線未獲準管理 SSH 資源。請使用 Server 操作者授權了 Runner 能力的配對碼。"],
} as const;

export type RunnerCapabilitiesKey = keyof typeof RUNNER_CAPABILITIES_MESSAGES;
export function runnerCapabilitiesText(locale: string, key: RunnerCapabilitiesKey): string {
  const index = PRODUCT_LOCALES.indexOf(locale as typeof PRODUCT_LOCALES[number]);
  return RUNNER_CAPABILITIES_MESSAGES[key][index < 0 ? 0 : index];
}
export function useRunnerCapabilitiesText() {
  const { locale } = useLocale();
  return (key: RunnerCapabilitiesKey) => runnerCapabilitiesText(locale, key);
}
