import { useLocale } from "./locale";
import { PRODUCT_LOCALES } from "./product";
const TEXT = {
  advanced: ["Advanced deployment options", "高级部署选项", "Erweiterte Bereitstellungsoptionen", "Options de déploiement avancées", "高度なデプロイ設定", "고급 배포 옵션", "高階部署選項"],
  migrationHelp: ["Keep your existing Server, projects and connection credentials. New migrations use sign-in startup; interrupted migrations resume their saved startup mode. No new Tunnel credentials are needed.", "保留原来的 Server、项目和连接凭据。新的迁移默认登录后启动；中断的迁移沿用已保存的启动方式。无需重新填写 Tunnel 凭据。", "Server, Projekte und Zugangsdaten bleiben erhalten. Neue Migrationen starten bei Anmeldung; unterbrochene behalten den gespeicherten Modus. Keine neuen Tunnel-Zugangsdaten nötig.", "Conservez le Server, les projets et les identifiants existants. Les nouvelles migrations démarrent à la connexion ; les migrations interrompues gardent leur mode enregistré. Aucun nouvel identifiant Tunnel requis.", "既存の Server、プロジェクト、接続情報を保持します。新規移行はログイン時起動を使用し、中断された移行は保存済み設定で再開します。Tunnel 情報の再入力は不要です。", "기존 Server, 프로젝트와 연결 자격 증명을 유지합니다. 새 마이그레이션은 로그인 시 시작하고 중단된 마이그레이션은 저장된 모드를 사용합니다. 새 Tunnel 자격 증명은 필요하지 않습니다.", "保留原來的 Server、專案和連線憑據。新的遷移預設登入後啟動；中斷的遷移沿用已儲存的啟動方式。無需重新填寫 Tunnel 憑據。"],
  title: ["Background startup", "后台启动方式", "Hintergrundstart", "Démarrage en arrière-plan", "バックグラウンド起動", "백그라운드 시작", "背景啟動方式"],
  user: ["When I sign in (recommended)", "我登录后启动（推荐）", "Bei meiner Anmeldung (empfohlen)", "À ma connexion (recommandé)", "ログイン時（推奨）", "로그인할 때 (권장)", "我登入後啟動（推薦）"],
  system: ["At computer startup (advanced)", "计算机启动时（高级）", "Beim Systemstart (erweitert)", "Au démarrage de l’ordinateur (avancé)", "コンピュータ起動時（高度な設定）", "컴퓨터 시작 시 (고급)", "電腦啟動時（高階）"],
  userHelp: ["Uses your own service manager, with no service password. macOS and Windows require a signed-in session; Linux logout persistence depends on linger. No system-service fallback.", "使用你的用户级服务，无需服务账户密码。macOS、Windows 需要保持登录；Linux 退出后继续运行取决于 linger。不会自动改装成系统服务。", "Eigene Benutzerverwaltung, ohne Dienstpasswort. macOS/Windows benötigen eine angemeldete Sitzung; Linux hängt von linger ab. Kein Systemdienst-Fallback.", "Services de votre session, sans mot de passe de service. Session connectée requise sur macOS/Windows ; linger détermine la persistance sous Linux. Aucun basculement système.", "サービス用パスワード不要のユーザー管理を使用します。macOS/Windows はログイン中のみ、Linux は linger に依存します。システムサービスへの自動切替はありません。", "서비스 암호 없이 사용자 서비스를 사용합니다. macOS/Windows는 로그인 세션이 필요하며 Linux는 linger 설정에 따릅니다. 시스템 서비스로 자동 전환하지 않습니다.", "使用你的使用者級服務，無需服務賬戶密碼。macOS、Windows 需要保持登入；Linux 退出後繼續執行取決於 linger。不會自動改裝成系統服務。"],
  systemHelp: ["For always-on or remotely managed machines, not the recommended Desktop mode. Runs before sign-in and requires administrator authorization. Windows services use different filesystem and session permissions; Runner may need an account password and cannot directly use your interactive desktop. Existing services are never adopted automatically.", "适合长期在线或远程托管的机器，不是普通 Desktop 的推荐模式。登录前运行，需要管理员授权。Windows 服务的文件和会话权限与桌面不同；Runner 可能需要账户密码，不能直接使用你的交互桌面。不会自动接管已有服务。", "Für dauerhaft aktive oder fernverwaltete Rechner, nicht der empfohlene Desktop-Modus. Start vor Anmeldung mit Administratorfreigabe. Windows-Dienste haben andere Datei- und Sitzungsrechte; Runner kann ein Passwort benötigen und nutzt nicht direkt den Desktop. Keine automatische Dienstübernahme.", "Pour les machines toujours actives ou administrées à distance, pas le mode Desktop recommandé. Démarre avant connexion avec autorisation administrateur. Droits de fichiers et de session différents sous Windows ; le Runner peut exiger un mot de passe et ne contrôle pas directement le bureau interactif. Aucun service existant adopté automatiquement.", "常時稼働・遠隔管理向けで、通常の Desktop には推奨しません。ログイン前に起動し管理者認可が必要です。Windows サービスはファイル・セッション権限が異なり、Runner はパスワードが必要な場合があり対話デスクトップを直接使用できません。既存サービスは自動取得しません。", "상시 실행 또는 원격 관리용이며 일반 Desktop 권장 모드가 아닙니다. 로그인 전에 실행되며 관리자 승인이 필요합니다. Windows 서비스의 파일·세션 권한은 다르고 Runner는 암호가 필요할 수 있으며 대화형 데스크톱을 직접 사용하지 못합니다. 기존 서비스를 자동 인수하지 않습니다.", "適合長期在線或遠端託管的機器，不是一般 Desktop 的推薦模式。登入前執行，需要管理員授權。Windows 服務的檔案和工作階段權限與桌面不同；Runner 可能需要賬戶密碼，不能直接使用你的互動桌面。不會自動接管已有服務。"],
} as const;
export function useServiceScopeText() {
  const { locale } = useLocale();
  const index = PRODUCT_LOCALES.indexOf(locale as typeof PRODUCT_LOCALES[number]);
  return (key: keyof typeof TEXT) => TEXT[key][index < 0 ? 0 : index];
}
