//! Runner-owned POSIX/search script execution.

use super::*;

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_internal_search_script_with_profiles_and_execution_state(
    generation: u64,
    policy: &RunnerPolicy,
    shell: &ShellConfig,
    project_registry_dir: &Path,
    cache: &PreparedShellProfileCache,
    cwd: Option<&str>,
    script: &str,
    timeout_secs: u64,
    stop_requested: Option<&AtomicBool>,
) -> ShellCommandResult {
    run_internal_posix_script_impl(
        generation,
        policy,
        shell,
        project_registry_dir,
        cache,
        cwd,
        script,
        timeout_secs,
        stop_requested,
        true,
    )
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn run_internal_posix_script_with_profiles_and_execution_state(
    generation: u64,
    policy: &RunnerPolicy,
    shell: &ShellConfig,
    project_registry_dir: &Path,
    cache: &PreparedShellProfileCache,
    cwd: Option<&str>,
    script: &str,
    timeout_secs: u64,
    stop_requested: Option<&AtomicBool>,
) -> ShellCommandResult {
    run_internal_posix_script_impl(
        generation,
        policy,
        shell,
        project_registry_dir,
        cache,
        cwd,
        script,
        timeout_secs,
        stop_requested,
        false,
    )
}

#[allow(clippy::too_many_arguments)]
pub(super) fn run_internal_posix_script_impl(
    generation: u64,
    policy: &RunnerPolicy,
    shell: &ShellConfig,
    project_registry_dir: &Path,
    cache: &PreparedShellProfileCache,
    cwd: Option<&str>,
    script: &str,
    timeout_secs: u64,
    stop_requested: Option<&AtomicBool>,
    search_compat: bool,
) -> ShellCommandResult {
    #[cfg(not(windows))]
    let _ = search_compat;
    #[cfg(not(windows))]
    {
        let payload = ShellScriptPayload {
            language: ShellScriptLanguage::Sh,
            script: script.to_string(),
            args: Vec::new(),
        };
        return run_script_with_profiles_and_execution_state(
            generation,
            policy,
            shell,
            project_registry_dir,
            cache,
            cwd,
            &payload,
            None,
            timeout_secs,
            stop_requested,
        );
    }

    #[cfg(windows)]
    {
        // WebCodex-generated POSIX programs never inherit the configured shell
        // parser. Native Windows Bash launchers map the process cwd; `bash -s`
        // consumes the generated bytes directly from stdin without asking Bash
        // to interpret a Windows temporary-script path.
        if !policy.allow_raw_shell {
            let subject = if search_compat {
                "internal search script"
            } else {
                "internal POSIX script"
            };
            return ShellCommandResult::not_started(CommandResult {
                exit_code: None,
                stdout: None,
                stderr: None,
                duration_ms: Some(0),
                error: Some(format!(
                    "{subject} execution is disabled by local Runner policy"
                )),
            });
        }
        if script.is_empty() {
            let subject = if search_compat {
                "internal search script"
            } else {
                "internal POSIX script"
            };
            return ShellCommandResult::not_started(CommandResult {
                exit_code: None,
                stdout: None,
                stderr: None,
                duration_ms: Some(0),
                error: Some(format!("{subject} is empty; command was not started")),
            });
        }
        let cwd_path = cwd
            .map(PathBuf::from)
            .unwrap_or_else(|| std::env::current_dir().unwrap_or_else(|_| PathBuf::from("/")));
        if let Err(error) = cwd_allowed(policy, &cwd_path) {
            return ShellCommandResult::not_started(CommandResult {
                exit_code: None,
                stdout: None,
                stderr: None,
                duration_ms: Some(0),
                error: Some(error),
            });
        }
        let timeout_secs = timeout_secs.min(policy.max_timeout_secs).max(1);
        let start = Instant::now();
        let profile = match resolve_prepared_shell_profile(
            generation,
            shell,
            project_registry_dir,
            &cwd_path,
            cwd.is_some(),
            cache,
            stop_requested,
        ) {
            Ok(profile) => profile,
            Err(error) => {
                return ShellCommandResult::not_started(CommandResult {
                    exit_code: None,
                    stdout: None,
                    stderr: None,
                    duration_ms: Some(start.elapsed().as_millis() as u64),
                    error: Some(error),
                })
            }
        };
        let interpreter =
            match resolve_windows_internal_posix_interpreter(shell, profile.as_deref()) {
                Ok(interpreter) => interpreter,
                Err(error) => {
                    return ShellCommandResult::not_started(CommandResult {
                        exit_code: None,
                        stdout: None,
                        stderr: None,
                        duration_ms: Some(start.elapsed().as_millis() as u64),
                        error: Some(error),
                    })
                }
            };
        let mut command = Command::new(interpreter);
        command.arg("-s");
        match profile.as_deref() {
            Some(profile) => apply_env_snapshot(&mut command, &profile.env_snapshot),
            None => {
                if let Err(error) = apply_shell_environment(&mut command, shell) {
                    return ShellCommandResult::not_started(CommandResult {
                        exit_code: None,
                        stdout: None,
                        stderr: None,
                        duration_ms: Some(start.elapsed().as_millis() as u64),
                        error: Some(error),
                    });
                }
            }
        }
        let script = if search_compat {
            // WSL/Git-Bash interop may expose a host ripgrep binary as `rg.exe`
            // rather than `rg`. Keep the existing search script and its rg-first
            // semantics unchanged by providing a process-local function only when
            // no native `rg` command is already visible. Relative project paths are
            // preserved across the Windows/Bash cwd mapping.
            format!(
                "if ! command -v rg >/dev/null 2>&1 && command -v rg.exe >/dev/null 2>&1; then rg() {{ command rg.exe --path-separator / \"$@\"; }}; fi\n{script}"
            )
        } else {
            script.to_string()
        };
        let spawn_error = if search_compat {
            "failed to spawn internal search interpreter"
        } else {
            "failed to spawn internal POSIX interpreter"
        };

        execute_configured_command(
            policy,
            command,
            &cwd_path,
            Some(&script),
            timeout_secs,
            stop_requested,
            start,
            spawn_error,
            None,
        )
    }
}
