use super::RouteAuth::AuthMiddleware;
use super::{
    route, AuditClass::*, OpenApiVisibility::*, RouteId::*, RouteMethod::*, RouteSpec,
    RouteSurface::*,
};
use crate::auth::scopes::OAuthRouteScopePolicy::*;

pub(super) const ROUTES: &[RouteSpec] = &[
    route(
        ShellAgentRegister,
        Post,
        "/api/shell/agent/register",
        AgentSurface,
        AgentTransport,
        Hidden,
        Other,
        AuthMiddleware,
    ),
    route(
        ShellAgentPoll,
        Post,
        "/api/shell/agent/poll",
        AgentSurface,
        AgentTransport,
        Hidden,
        Other,
        AuthMiddleware,
    ),
    route(
        ShellAgentResult,
        Post,
        "/api/shell/agent/result",
        AgentSurface,
        AgentTransport,
        Hidden,
        Other,
        AuthMiddleware,
    ),
    route(
        ShellAgentPersistentShellResult,
        Post,
        "/api/shell/agent/persistent_shell_result",
        AgentSurface,
        AgentTransport,
        Hidden,
        Other,
        AuthMiddleware,
    ),
    route(
        ShellAgentJobUpdate,
        Post,
        "/api/shell/agent/job_update",
        AgentSurface,
        AgentTransport,
        Hidden,
        Other,
        AuthMiddleware,
    ),
    route(
        AgentsWs,
        Get,
        "/api/agents/ws",
        AgentSurface,
        AgentTransport,
        Hidden,
        Other,
        AuthMiddleware,
    ),
];
