use super::RouteAuth::AuthMiddleware;
use super::{route, AuditClass::*, RouteId::*, RouteMethod::*, RouteSpec, RouteSurface::*};
use webcodex_core::authority::OAuthRouteScopePolicy::*;

pub(super) const ROUTES: &[RouteSpec] = &[
    route(
        RunnerRegister,
        Post,
        "/api/shell/agent/register",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
    route(
        RunnerOffline,
        Post,
        "/api/shell/agent/offline",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
    route(
        RunnerPoll,
        Post,
        "/api/shell/agent/poll",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
    route(
        RunnerResult,
        Post,
        "/api/shell/agent/result",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
    route(
        RunnerPersistentShellResult,
        Post,
        "/api/shell/agent/persistent_shell_result",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
    route(
        RunnerJobUpdate,
        Post,
        "/api/shell/agent/job_update",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
    route(
        RunnerWs,
        Get,
        "/api/agents/ws",
        AgentSurface,
        RunnerTransport,
        Other,
        AuthMiddleware,
    ),
];
