// Deterministic non-secret fixtures. Shapes: desktop topology.ts / App.test.tsx;
// src/runtime_console_http.rs; crates/webcodex-workflow-session/src/console.rs.
export const now=Date.now(), key='4700'.repeat(16);
export const attention={open_guidance:0,open_questions:1,open_risks:0,open_todos:0};
export const aggregate={retained_sessions:2,returned_sessions:2,sessions_truncated:false,active_sessions:1,running_sessions:1,latest_updated_at:Math.floor(now/1000),attention};
export const projects=['alpha','beta'].map(n=>({id:`agent:fixture-runner:${n}`,client_id:'fixture-runner',name:`Fixture ${n}`,path:`/fixture/${n}`,connected:true,agent_status:'online',sessions:aggregate}));
export const overview={work:{exploration:2,edits:1,reviews:0,validations:1,runs:1,history_complete:true,history_truncated:false},validation:{state:'passed',latest_kind:'tests',latest_at:Math.floor(now/1000),unresolved_failure_count:0,tests_run_count:3,history_complete:true,history_truncated:false},attention};
export const sessions=[{session_id:'wc_sess_fixture470_active',title:'Fixture workspace review',lifecycle:'active',mode:'normal',updated_at:Math.floor((now-0)/1000),running_call:true,running_jobs:1,running_jobs_complete:true,overview},{session_id:'wc_sess_fixture470_closed',title:'Fixture completed checks',lifecycle:'closed',mode:'normal',updated_at:Math.floor((now-60000)/1000),running_call:false,running_jobs:0,running_jobs_complete:true,overview:{...overview,attention:{...attention,open_questions:0}}}];
export const activity={kind:'Edited',tool:'apply_patch',state:'succeeded',job_handoff:false,started_at:Math.floor((now-10000)/1000),finished_at:Math.floor((now-9000)/1000),duration_ms:1000,summary:'Fixture retained file edit',paths:['src/fixture.ts']};
export const windowSummary={client_window_key:key,last_project:projects[0].id,source:'openai-session',first_seen_at_ms:now-3600000,last_seen_at_ms:now,last_tool_call_at_ms:now,last_meaningful_activity_at_ms:now,active_count:1,linked_session_count:1,recorder_gap_count:0};
export const windowActivity={started_at_ms:now-1000,ended_at_ms:now-950,duration_ms:50,service_ms:50,method:'tools/call',tool_name:'read_files',activity_presentation:'work',activity_kind:'read',project:projects[0].id,status:'success',meaningful:true,server_trace_id:'fixture-trace-470',workflow_sessions:[]};
const goalId='wc_goal_1234567890abcdef';
const goalSteps=[{id:'inspect',title:'Inspect workspace',status:'completed',updated_at_unix_ms:now-60000},{id:'design',title:'Refine interface',status:'in_progress',updated_at_unix_ms:now},{id:'verify',title:'Verify accessibility',status:'pending',updated_at_unix_ms:now}];
const goalItem={goal_id:goalId,title:'Refresh the WebCodex workspace',lifecycle:'active',revision:3,updated_at_unix_ms:now,agent_task_count:0,workflow_session_count:1,total_step_count:3,completed_step_count:1,current_step_id:'design',current_step_title:'Refine interface',progress_summary:'Improving the daily workspace',project_ids:[projects[0].id]};
const goalDetail={goal:{summary:{goal_id:goalId,title:goalItem.title,lifecycle:'active',revision:3,created_at_unix_ms:now-3600000,updated_at_unix_ms:now,terminal_at_unix_ms:null,agent_task_count:0,workflow_session_count:1},plan:{completion_conditions:['Review screenshots'],steps:goalSteps,progress_summary:goalItem.progress_summary,checkpoint_at_unix_ms:now},objective:'Make the daily workspace clearer and more comfortable to use.',controller_agent_id:null,terminal_reason:null,correlations:[]},goal_plan:{version:3,goal_id:goalId,title:goalItem.title,total_step_count:3,completed_step_count:1,current_step_id:'design',steps:goalSteps,progress_summary:goalItem.progress_summary,checkpoint_at_unix_ms:now,controller_agent_id:null,lifecycle:'active',revision:3,updated_at_unix_ms:now,terminal_at_unix_ms:null,agent_task_count:0,workflow_session_count:1,activity:{available:true,state:'active',idle_threshold_ms:300000,observation_lease_ms:60000,linked_window_count:0,active_meaningful_request_count:0,coverage_partial:false},continuity:{available:true,state:'ready',production_auto_resume_available:true,host_delivery:'ready',fresh_turn:'ready'}},projects,sessions:[{session_id:sessions[0].session_id,title:sessions[0].title,lifecycle:'active',mode:'normal',updated_at:sessions[0].updated_at,running_jobs:1,project_id:projects[0].id,project_name:projects[0].name,client_id:'fixture-runner'}],tasks:[],waits:[],waits_truncated:false,agents:[],windows:[]};
export function webResponse(route,p={}) {
 switch(route){
 case 'goals':return {goals:[goalItem],total:1,source_total:1,truncated:false};
 case 'goal':return goalDetail;
 case 'project-git':return {branch:'codex/fixture-ui',clean:true,git_available:true};
 case 'overview': return {service:'FIXTURE ONLY — WebCodex',version:'0.4.1',build_git_commit:'fixture470',build_git_dirty:false,runner_count:1,runners_online:1,runners_stale:0,runners_unavailable:0,source_mismatched_runners:0,mixed_builds_present:false,active_jobs:1,projects_available:true,visible_projects:2,projects_truncated:false,workflow_sessions:{active:1,running:1,...attention,projects_scanned:2,projects_total:2,truncated:false},recent_sessions:{sessions:sessions.map(s=>({...s,client_id:'fixture-runner',project_id:projects[0].id,project_name:projects[0].name})),returned:2,candidate_count:2,truncated:false,scan_truncated:false},runners:[{client_id:'fixture-runner',connected:true,status:'online',transport:'websocket',runner_protocol_generation:1,last_seen_age_secs:0,version:'0.4.1',build_git_commit:'fixture470',build_git_dirty:false,source_alignment:'same',version_matches_server:true,active_jobs:1,job_concurrency_limit:4,jobs_running:1,jobs_queued:0,projects_scanned:2,projects_scan_partial:false,sessions:aggregate}],projects};
 case 'projects':return {projects,total:2,truncated:false};
 case 'workflow-sessions':return {sessions,total:2,returned:2,truncated:false};
 case 'workflow-session':return {...sessions.find(s=>s.session_id===p.session_id),created_at:Math.floor((now-3600000)/1000),activity:[activity],activity_total:1,activity_returned:1,activity_truncated:false,window_activity_available:true,linked_windows:[],window_activity_after_last_session_record:[]};
 case 'windows':return {windows:[windowSummary],returned:1,total:1,truncated:false,visibility:{scope:'global'}};
 case 'window':return {...windowSummary,active_requests:[{server_trace_id:'fixture-active-trace',method:'tools/call',tool_name:'run_process',project:projects[0].id,started_at_ms:now,elapsed_ms:500}],linked_sessions:[{workflow_session_id:sessions[0].session_id,project:projects[0].id,first_linked_at_ms:now-30000,last_linked_at_ms:now,relations:['work_on_project'],relation_count:1,title:sessions[0].title,lifecycle:'active'}],sessions_returned:1,sessions_truncated:false,activity:[windowActivity],activity_returned:1,activity_truncated:false,visibility:{scope:'global'}};
 case 'workflow-session-observe':return {session_id:p.session_id,messages:[],observation_token:'fixture-observation',changed:false,wait_outcome:'timeout',waited_ms:1000,history_lost:false,has_more:false};
 case 'workflow-session-messages':return {session_id:p.session_id,messages:[]};
 case 'communication/agents':return {agents:[],returned:0,total:0,truncated:false};
 case 'communication/conversations':return {conversations:[],returned:0,total:0,truncated:false};
 default:throw Error('Unimplemented fixture route '+route);
 }
}
export const adminDashboard = {
  overview: {version:'0.4.2',build_commit:'fixture-ui',authority_mode:'admin',runners_online:1,runners_total:1,projects_online:2,projects_total:2,active_jobs:1,version_compatibility:'compatible'},
  diagnostics: {service:'FIXTURE ONLY',server_build:'fixture-ui',project_count:2},
  devices: [{display_name:'Fixture Runner',client_id:'fixture-runner',status:'online',transport:'websocket',hostname:'fixture.local',last_seen:'just now',capabilities:['projects','jobs'],project_count:2,active_jobs:1,compatibility:'compatible'}],
  projects: [{id:'agent:fixture-runner:alpha',name:'Fixture alpha',client_id:'fixture-runner',path:'/fixture/alpha',lifecycle_status:'enabled',active_jobs:1,git_available:true,allow_patch:true,shell_profile_status:'ready',compatibility:'compatible',console_hint:'open',revision:'fixture-revision',actions:{enable:false,disable:true,unregister:true}}],
  activity: [{created_at:'just now',kind:'project_observed',project_id:'agent:fixture-runner:alpha',status:'succeeded'}],
};
export function desktopState(disconnected=false){const roots=['alpha','beta'].map(n=>({path:`/fixture/${n}`,allowed_root:`/fixture/${n}`,is_git_repository:true,runtime_project_id:`agent:fixture-runner:${n}`}));return {saved_projects:roots,topology:{experience:'full',server:{kind:'local'},runner:{kind:'local'},exposure:{kind:'open_ai_tunnel'},enrollment:{kind:'managed_pairing'}},readiness:{server:'ready',runner:'ready',exposure:disconnected?'disabled':'remote_ready',project:'ready',runtime_ready:true,ready_for_chatgpt:!disconnected,summary:'FIXTURE ONLY',summary_kind:disconnected?'connection_unverified':'ready_for_chat_gpt'},project:roots[0],binaries:{directory:'/fixture/bin',version:'0.4.1',git_commit:'fixture470',source:'fixture'},powershell_runtime:{pwsh_available:true,windows_powershell_available:false},chatgpt_activity:{observed:!disconnected,last_meaningful_activity_at_ms:now},quick_share:null,regular_tunnel:disconnected?null:{provider:'openai',status:'ready',clipboard_state:'not_copied',clipboard_contains:'none',ready_for_chatgpt:true},current_operation:null,activity_sequence:0,openai_tunnel_configured:true,openai_tunnel_config:{tunnel_id_present:true,api_key_present:true,source:'file',saved_tunnel_id:'tunnel_fixture470',effective_tunnel_id:'tunnel_fixture470'},regular_tunnel_available:true,runtime_autostart:false,preferred_connection:'open_ai_tunnel',tunnel_proxy:{mode:'auto',custom_url:null,effective_source:'direct',effective_url:null,detected_url:null}};}
