import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { startFixture, sleep } from '../tests/chrome-fixture.mjs';
import { PluginClient, cdpRequest, evaluate } from '../tests/rpc-client.mjs';
const root = fileURLToPath(new URL('../', import.meta.url));
const fixture = await startFixture({ headed: process.env.WC_TEST_HEADED === '1' });
const config = path.join(fixture.dir, 'plugin.local.json');
await fs.writeFile(config, JSON.stringify({ executable: process.env.WC_TEST_AGENT_BROWSER || 'agent-browser', connection: fixture.port }), { mode: 0o600 });
const plugin = new PluginClient(config);
const checks = [];
let screenshot;
function pass(label) { checks.push(label); console.log('PASS ' + label); }
async function expectError(name, args, allowed) {
  const r = await plugin.raw(name, args);
  assert.equal(r.isError, true, 'Expected a known rejected operation');
  assert(allowed.includes(r.structuredContent.code), 'Unexpected error code: ' + r.structuredContent.code);
}
async function currentTargets() { return (await (await fetch(`http://127.0.0.1:${fixture.port}/json/list`)).json()).filter(t => t.type === 'page'); }
try {
  const baseline = await currentTargets();
  assert.equal((await plugin.init()).protocolVersion, 'webcodex-plugin-v1');
  const catalog = await plugin.request('tools/list', {});
  assert.equal(catalog.tools.length, 16);
  assert(!catalog.tools.some(t => /eval|shell|cookie|storage/.test(t.name)));
  assert.equal((await currentTargets()).length, baseline.length);
  pass('Native Plugin initialize/list are side-effect free; 16 typed tools');
  const status = await plugin.call('browser_status'); assert.equal(status.backend_version, '0.38.1'); assert.equal(status.connection_state, 'not_connected');
  pass('Backend version and offline connection status');
  const connection = await plugin.call('browser_connect');
  assert.equal(connection.connection_state, 'connected');
  const blank = connection.page.page_id;
  const targetsAfterConnect = await currentTargets();
  assert.equal(targetsAfterConnect.length, baseline.length + 1);
  for (const target of baseline) assert(targetsAfterConnect.some(t => t.id === target.id && t.url === target.url));
  pass('Attach to external Chrome; pinned blank tab preserves pre-existing tabs');
  const tabs = await plugin.call('browser_tabs'); const preexisting = tabs.pages.find(p => !p.created_by_plugin);
  await expectError('browser_close_page', { page_id: preexisting.page_id }, ['not_owned']);
  pass('Reject closing pre-existing user tab');
  await expectError('browser_open', { url: 'file:///private' }, ['invalid_url']);
  pass('Reject local-file/browser-internal navigation');
  const opened = await plugin.call('browser_open', { url: fixture.url });
  const page = opened.page.page_id, url = fixture.url + '/';
  let snap = await plugin.call('browser_snapshot', { page_id: page });
  let input = snap.elements.find(e => e.role === 'textbox' && e.name.trim() === 'Name');
  assert(input, 'Live textbox was not discovered');
  const literal = 'WebCodex 中文 --config=literal "quoted"';
  await plugin.call('browser_fill', { page_id: page, snapshot_id: snap.snapshot_id, element_id: input.element_id, text: literal });
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#name").value'), literal);
  pass('Real textbox fill; Unicode/quotes/flag-like text stay literal');
  snap = await plugin.call('browser_snapshot', { page_id: page });
  const plan = snap.elements.find(e => e.role === 'combobox' && e.name.trim() === 'Plan');
  await plugin.call('browser_select_option', { page_id: page, snapshot_id: snap.snapshot_id, element_id: plan.element_id, value: 'pro' });
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#plan").value'), 'pro');
  pass('Real select option uses structured combobox action');
  snap = await plugin.call('browser_snapshot', { page_id: page });
  const agree = snap.elements.find(e => e.role === 'checkbox' && e.name.trim() === 'Agree');
  await plugin.call('browser_set_checked', { page_id: page, snapshot_id: snap.snapshot_id, element_id: agree.element_id, checked: true });
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#agree").checked'), true);
  pass('Real checkbox state uses structured check action');
  await expectError('browser_fill', { page_id: page, snapshot_id: snap.snapshot_id, element_id: input.element_id, text: 'duplicate' }, ['unknown_element', 'stale_snapshot']);
  pass('Consumed snapshot is rejected, not replayed');
  snap = await plugin.call('browser_snapshot', { page_id: page });
  let button = snap.elements.find(e => e.role === 'button' && e.name === 'Greet');
  await plugin.call('browser_click', { page_id: page, snapshot_id: snap.snapshot_id, element_id: button.element_id });
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#result").textContent'), 'Hello ' + literal);
  pass('Real button click updates DOM, independently verified over CDP');
  snap = await plugin.call('browser_snapshot', { page_id: page });
  assert(snap.text.includes('Hello ' + literal.replace(/"/g, '\\"')) || snap.text.includes('Hello ' + literal), 'Full snapshot must expose the actual greeting result, not only interactive controls');
  pass('Full semantic snapshot includes static result text for outcome verification');
  await plugin.call('browser_reload', { page_id: page });
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#result").textContent'), 'Ready');
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#name").value'), '');
  pass('Real reload refreshes the exact selected page and invalidates prior state');
  snap = await plugin.call('browser_snapshot', { page_id: page });
  button = snap.elements.find(e => e.role === 'button' && e.name === 'Greet');
  const oldTime = await evaluate(fixture, url, 'performance.timeOrigin');
  await cdpRequest(fixture, url, 'Page.reload');
  for (let i = 0; i < 40; i++) { await sleep(100); try { if ((await evaluate(fixture, url, 'performance.timeOrigin')) !== oldTime) break; } catch {} }
  await expectError('browser_click', { page_id: page, snapshot_id: snap.snapshot_id, element_id: button.element_id }, ['stale_snapshot']);
  assert.equal(await evaluate(fixture, url, 'document.querySelector("#result").textContent'), 'Ready');
  pass('Same-URL reload rejects stale action before click');
  snap = await plugin.call('browser_snapshot', { page_id: page }); button = snap.elements.find(e => e.name === 'Greet');
  await evaluate(fixture, url, 'document.querySelector("#greet").textContent="Changed action"');
  await expectError('browser_click', { page_id: page, snapshot_id: snap.snapshot_id, element_id: button.element_id }, ['stale_snapshot']);
  pass('Semantic page change rejects stale element');
  screenshot = await plugin.call('browser_screenshot', { page_id: page });
  assert.equal(screenshot.mime_type, 'image/png'); assert(screenshot.bytes > 1000); assert(screenshot.width > 300); assert(screenshot.height > 300);
  await fs.access(path.join(root, screenshot.artifact_path));
  pass('Real PNG screenshot artifact with dimensions/hash');
  await plugin.call('browser_scroll', { page_id: page, direction: 'down', pixels: 600 });
  assert((await evaluate(fixture, url, 'scrollY')) > 0);
  snap = await plugin.call('browser_snapshot', { page_id: page, interactive_only: true });
  await plugin.call('browser_press', { page_id: page, snapshot_id: snap.snapshot_id, key: 'Escape' });
  pass('Real scrolling and page keyboard input');
  await plugin.call('browser_navigate', { page_id: page, url: fixture.url + '/second' });
  snap = await plugin.call('browser_snapshot', { page_id: page });
  assert(snap.text.includes('WebCodex agent-browser live test'));
  const second = await plugin.call('browser_open', { url: fixture.url + '/third' });
  const snap2 = await plugin.call('browser_snapshot', { page_id: second.page.page_id });
  await expectError('browser_click', { page_id: page, snapshot_id: snap2.snapshot_id, element_id: snap2.elements.find(e => e.role === 'button').element_id }, ['unknown_element', 'stale_snapshot']);
  pass('Navigation and exact cross-tab snapshot isolation');
  const large = await plugin.call('browser_open', { url: fixture.url + '/large' });
  const largeSnap = await plugin.call('browser_snapshot', { page_id: large.page.page_id });
  assert.equal(largeSnap.snapshot_mode, 'interactive_auto'); assert.equal(largeSnap.auto_compacted, true);
  assert(largeSnap.elements.some(e => e.role === 'link' && e.name === 'Action 0'));
  assert(!largeSnap.text.includes('Static paragraph 80'));
  pass('Large real page automatically compacts to interactive controls');
  await plugin.call('browser_close_page', { page_id: large.page.page_id });
  await plugin.call('browser_close_page', { page_id: second.page.page_id });
  await plugin.call('browser_close_page', { page_id: page });
  await plugin.call('browser_close_page', { page_id: blank });
  assert.equal((await plugin.call('browser_disconnect')).chrome_closed, false);
  const after = await currentTargets();
  assert.equal(after.length, baseline.length);
  for (const target of baseline) assert(after.some(t => t.id === target.id && t.url === target.url));
  pass('Close only plugin-owned tabs; disconnect leaves external Chrome alive');
  await fs.mkdir(path.join(root, '.local'), { recursive: true, mode: 0o700 });
  const report = { passed: true, tested_at: new Date().toISOString(), backend_version: status.backend_version,
    chrome_version: (await (await fetch(`http://127.0.0.1:${fixture.port}/json/version`)).json()).Browser,
    checks, screenshot, daily_profile_tested: false, gateway_tested: false };
  await fs.writeFile(path.join(root, '.local/live-report.json'), JSON.stringify(report, null, 2) + '\n', { mode: 0o600 });
  console.log('PASS ' + checks.length + ' real-Chrome checks. Report: .local/live-report.json');
} finally { await plugin.call('browser_disconnect').catch(() => {}); await plugin.stop(); await fixture.cleanup(); }
