use crate::input_schema_for_tool;
#[cfg(test)]
use serde_json::Value;

mod memory;
mod skills;

use super::super::tool_definition::{
    lookup_tool_definition, model_visible_tool_definitions, runtime_tool_operator_extension_family,
    ToolDefinition, ToolOperatorExtensionFamily,
};
use super::super::tool_spec::ToolSpec;
use super::{output_schema_for_tool, tool_annotations};
use std::collections::BTreeSet;

pub fn registered_tool_specs() -> Vec<ToolSpec> {
    resolve_tool_specs(model_visible_tool_definitions())
}

fn operator_extension_specs(
    specs: Vec<ToolSpec>,
    family: ToolOperatorExtensionFamily,
) -> Vec<ToolSpec> {
    specs
        .into_iter()
        .filter(|spec| runtime_tool_operator_extension_family(&spec.name) == Some(family))
        .collect()
}

/// Goal Plan observation/synchronization contract. The single App-only tool is
/// explicitly effectful: Server-owned stall revalidation may atomically create
/// one durable Attention/Wake before returning the final bounded projection.
pub fn goal_plan_app_tool_specs() -> Vec<ToolSpec> {
    vec![tool_spec(
        "goal_plan_sync",
        "App-only exact Goal Plan synchronization from the current Host Window. Accepts only goal_id; re-authorizes the Goal, recomputes bounded activity, and when inactivity is authoritatively eligible reuses the Server-owned Session/Window/Project/revision/request/coverage fences to atomically create at most one durable Attention/Wake per meaningful-work epoch before returning the final bounded projection. It never dispatches a Host turn directly.",
    )]
}

/// Read-only Work Result App primitives. Canonical definitions stay ModelHidden;
/// only the MCP Apps adapter projects live refresh, closeout sealing, and frozen lazy diff reads.
pub fn work_result_app_tool_specs() -> Vec<ToolSpec> {
    vec![
        tool_spec(
            "work_result_state",
            "App-only exact live Work Result refresh. Re-authorizes project + session_id and never records into the target Session. It returns live progress domains plus any retained immutable final-changes snapshot already sealed by a non-blocking finish_coding_task closeout; the refresh never creates or replaces that snapshot.",
        ),
        tool_spec(
            "changes_file_diff",
            "Work Result App-only bounded lazy read of one advertised path from the card's sealed final snapshot. Re-authorizes exact project + session, validates caller/snapshot/path binding, grants no authority, and never records the click into the target Session.",
        ),
    ]
}

/// Fixed MCP App Host-continuation coordination contract. Definitions remain
/// globally ModelHidden and deliberately stay outside the generic Stateless
/// operator-extension universe: only the MCP Apps adapter may project them.
pub fn agent_continuation_app_tool_specs() -> Vec<ToolSpec> {
    vec![
        tool_spec(
            "agent_wait_state",
            "App-only exact read of one caller-owned durable AgentWait. SQLite is authoritative; this polling call creates no Wake, changes no Wait lifecycle, grants no source authority, and must not count as meaningful Window activity.",
        ),
        tool_spec(
            "agent_continuation_bind",
            "App-only bind of one live View to one exact current Durable Agent Endpoint generation. Supply a stable binding_id generated by the View using 128 secure random bits (wc_host_binding_ plus canonical base64url-no-pad of 16 random bytes). It is the iframe/process-instance fence, never authority. Re-authorizes communication:manage on every call. Normal first bind requires the current process attachment; after Server restart, recovery remains limited to the exact durable binding fingerprint or a canonical Host ClientWindow continuity identity carried outside tool input. Retry a lost response with the same exact binding_id renews without revoking claims or resetting dispatch; a same-Window refreshed iframe may replace its older fence. A different Host Window, stale generation, expired Endpoint, or foreign principal fails closed. No durable continuation truth is created.",
        ),
        tool_spec(
            "agent_continuation_recover_endpoint",
            "App-only idempotent probe+replacement for one exact expired Durable Agent Endpoint. The stale Agent/Endpoint/generation and iframe binding_id are explicit, while same-Window authority comes only from the canonical Host ClientWindow sideband and cannot be self-asserted in tool input. A still-live controller is a no-op. Only natural expiry with matching durable Window continuity may atomically create generation+1; replay returns that same replacement and a different Window or already-successor controller fails closed.",
        ),
        tool_spec(
            "agent_continuation_state",
            "App-only exact Host heartbeat and sparse authoritative continuation-state refresh. Renews only the current exact Endpoint/View binding; stale Views fail closed.",
        ),
        tool_spec(
            "agent_continuation_wake_acquire",
            "App-only pre-fence acquire through the existing durable Wake claim state machine. Returns bounded safe identity only; claim fences and consume tokens remain private.",
        ),
        tool_spec(
            "agent_continuation_wake_prepare",
            "App-only crossing of the existing durable dispatch fence immediately before one Host ui/message attempt. Success returns the bounded exact automatic_message in structuredContent.output.app_protocol for this View only, including the one-shot consume token; never copy it to a card, model tool result, or generic context update. Custom ToolResult _meta is not required. Send exactly one ui/message for that Attempt. A timeout or missing/malformed successful envelope may already be post-fence: reconcile state and finish as delivery_unknown, never blindly retry prepare or dispatch.",
        ),
        tool_spec(
            "agent_continuation_wake_finish",
            "App-only record of ui/message dispatch acceptance or conservative post-fence delivery uncertainty. Dispatch acceptance never means model resumed; only exact consume_agent_wake proves the continuation turn ran.",
        ),
        tool_spec(
            "agent_continuation_unbind",
            "App-only best-effort withdrawal of one exact process-local View binding. Stale teardown cannot withdraw a replacement View; durable Wake reconciliation remains owned by the existing Endpoint/Wake state machine.",
        ),
    ]
}

/// Fixed Job-native MCP App Host-continuation coordination contract. Definitions remain
/// globally ModelHidden; only a UI-capable MCP adapter may project these five tools.
pub fn job_terminal_continuation_app_tool_specs() -> Vec<ToolSpec> {
    vec![
        tool_spec(
            "job_terminal_continuation_bind",
            "App-only bind of one live View to one exact caller-owned Job terminal wait. ClientWindow arrives only from Host sideband; binding_id is a process/View fence, never Job authority.",
        ),
        tool_spec(
            "job_terminal_continuation_state",
            "App-only bounded state read for one exact current Job terminal binding. Polling is View-internal and never substitutes for model-facing Job observation.",
        ),
        tool_spec(
            "job_terminal_continuation_prepare",
            "App-only crossing of the existing durable pending-to-prepared Job terminal delivery fence. Returns one bounded private automatic_message and exact attempt_id; never blindly retry after a missing or malformed post-fence response.",
        ),
        tool_spec(
            "job_terminal_continuation_finish",
            "App-only record of one prepared Host ui/message dispatch as dispatch_accepted or delivery_unknown. It never proves the fresh model turn already ran and never retries delivery.",
        ),
        tool_spec(
            "job_terminal_continuation_unbind",
            "App-only best-effort withdrawal of one exact process-local Job View binding. Pre-prepare teardown leaves pending recoverable; post-prepare teardown reconciles conservatively to delivery_unknown.",
        ),
    ]
}

/// Fixed admin-only forensic trace reader. It remains globally ModelHidden and
/// is projected only by capable Stateless MCP 2026 adapters.
pub fn operator_diagnostic_tool_specs() -> Vec<ToolSpec> {
    operator_extension_specs(
        vec![tool_spec(
            "read_tool_trace",
            "Admin-only bounded reader for Server-hosted full tool-request traces. Omit payload_index to list safe payload metadata first; then read one bounded JSON payload by index. Available only when full trace mode is enabled. Trace payloads may contain sensitive tool data and never grant execution authority.",
        )],
        ToolOperatorExtensionFamily::TraceDiagnostics,
    )
}

/// Fixed read-only project Memory runtime contract. Definitions remain hidden
/// from generic/GPT Action registries and are projected only by capable
/// Stateless MCP 2026 adapters.
pub fn memory_runtime_tool_specs() -> Vec<ToolSpec> {
    operator_extension_specs(
        memory::tool_specs(),
        ToolOperatorExtensionFamily::MemoryRuntime,
    )
}

/// Fixed project Memory mutation plus global Memory lifecycle contract. Durable
/// Memory/scope cardinality never changes this schema set. Each tool's canonical
/// ToolDefinition authority distinguishes project-scoped memory:manage from
/// admin-only lifecycle inspection/purge; permission evaluation remains independent.
pub fn memory_management_tool_specs() -> Vec<ToolSpec> {
    operator_extension_specs(
        memory::tool_specs(),
        ToolOperatorExtensionFamily::MemoryManagement,
    )
}

/// Fixed read-only Skill runtime contract. These definitions are deliberately
/// ModelHidden globally and are projected only by the capable Stateless MCP
/// 2026 adapter.
pub fn skill_runtime_tool_specs() -> Vec<ToolSpec> {
    operator_extension_specs(
        skills::tool_specs(),
        ToolOperatorExtensionFamily::SkillRuntime,
    )
}

/// Fixed Runner-global Skill-management contract. Package/version cardinality
/// never changes this schema set; the MCP adapter additionally requires explicit
/// operator authority before projecting these tools.
pub fn skill_management_tool_specs() -> Vec<ToolSpec> {
    operator_extension_specs(
        skills::tool_specs(),
        ToolOperatorExtensionFamily::SkillManagement,
    )
}

/// Canonical fixed Stateless MCP 2026 operator-extension universe. These specs
/// remain globally ModelHidden and are projected only by protocol-capability-aware
/// adapters and discovery. Keeping the composition here prevents tools/list,
/// Adaptive gateway admission, and tool_manifest from maintaining separate name sets.
pub fn stateless_operator_extension_tool_specs() -> Vec<ToolSpec> {
    skill_runtime_tool_specs()
        .into_iter()
        .chain(skill_management_tool_specs())
        .chain(memory_runtime_tool_specs())
        .chain(memory_management_tool_specs())
        .chain(operator_diagnostic_tool_specs())
        .collect()
}

fn resolve_tool_specs<'a>(
    definitions: impl IntoIterator<Item = &'a ToolDefinition>,
) -> Vec<ToolSpec> {
    let mut specs = Vec::new();
    let mut seen_definition_names = BTreeSet::new();
    for definition in definitions {
        if !seen_definition_names.insert(definition.name) {
            panic!(
                "{} model-visible ToolDefinition is duplicated",
                definition.name
            );
        }
        let model_spec = definition.model_spec.unwrap_or_else(|| {
            panic!(
                "{} model-visible ToolDefinition is missing model spec",
                definition.name
            )
        });
        specs.push(tool_spec(definition.name, model_spec.description));
    }
    specs
}

pub(super) fn tool_spec(name: &'static str, description: impl Into<String>) -> ToolSpec {
    debug_assert!(
        lookup_tool_definition(name).is_some(),
        "{name} ToolSpec is missing a ToolDefinition"
    );
    ToolSpec {
        name: name.to_string(),
        description: description.into(),
        input_schema: input_schema_for_tool(name),
        output_schema: output_schema_for_tool(name),
        annotations: tool_annotations(name),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn collect_schema_descriptions<'a>(value: &'a Value, out: &mut Vec<&'a str>) {
        match value {
            Value::Object(map) => {
                if let Some(description) = map.get("description").and_then(Value::as_str) {
                    out.push(description);
                }
                for nested in map.values() {
                    collect_schema_descriptions(nested, out);
                }
            }
            Value::Array(values) => {
                for nested in values {
                    collect_schema_descriptions(nested, out);
                }
            }
            _ => {}
        }
    }

    #[test]
    fn model_visible_definitions_own_all_registered_model_specs() {
        let definitions = model_visible_tool_definitions().collect::<Vec<_>>();
        let definition_names = definitions
            .iter()
            .map(|definition| definition.name)
            .collect::<BTreeSet<_>>();
        assert_eq!(
            definition_names.len(),
            definitions.len(),
            "model-visible ToolDefinition names must be unique"
        );
        for definition in &definitions {
            assert!(
                definition.model_spec.is_some(),
                "{} model-visible ToolDefinition must own description + input schema",
                definition.name
            );
        }

        let specs = registered_tool_specs();
        let spec_names = specs
            .iter()
            .map(|spec| spec.name.as_str())
            .collect::<BTreeSet<_>>();
        assert_eq!(
            spec_names.len(),
            specs.len(),
            "registered ToolSpecs must be unique"
        );
        assert_eq!(spec_names, definition_names);
        assert_eq!(specs.len(), definitions.len());
    }

    #[test]
    fn stateless_operator_extension_specs_are_one_unique_hidden_family_union() {
        let expected = skill_runtime_tool_specs()
            .into_iter()
            .chain(skill_management_tool_specs())
            .chain(memory_runtime_tool_specs())
            .chain(memory_management_tool_specs())
            .chain(operator_diagnostic_tool_specs())
            .map(|spec| spec.name)
            .collect::<Vec<_>>();
        let actual = stateless_operator_extension_tool_specs()
            .into_iter()
            .map(|spec| spec.name)
            .collect::<Vec<_>>();
        assert_eq!(
            actual, expected,
            "canonical extension ordering/families drifted"
        );

        let unique = actual.iter().map(String::as_str).collect::<BTreeSet<_>>();
        assert_eq!(
            unique.len(),
            actual.len(),
            "extension ToolSpecs must be unique"
        );
        let generic = registered_tool_specs()
            .into_iter()
            .map(|spec| spec.name)
            .collect::<BTreeSet<_>>();
        assert!(
            unique.iter().all(|name| !generic.contains(*name)),
            "Stateless operator extensions must remain outside registered_tool_specs: {unique:?}"
        );
    }

    #[test]
    fn register_project_definition_owned_model_spec_matches_exact_contract() {
        let actual = registered_tool_specs()
            .into_iter()
            .find(|spec| spec.name == "register_project")
            .expect("register_project spec");
        let expected = tool_spec(
            "register_project",
            "Register an existing directory, including a non-Git or ad-hoc workspace, as a Project on one Runner. Successful onboarding returns the canonical Runtime Project id and a Server-issued project_ref when a stable root identity is available. Use this when the directory already exists; policy still bounds allowed paths.",
        );
        assert_eq!(
            serde_json::to_value(actual).unwrap(),
            serde_json::to_value(expected).unwrap(),
            "definition-owned register_project ToolSpec must preserve name, description, input/output schemas, and annotations exactly"
        );
    }

    #[test]
    #[should_panic(
        expected = "register_project model-visible ToolDefinition is missing model spec"
    )]
    fn model_spec_omission_fails_closed() {
        let mut definition =
            *lookup_tool_definition("register_project").expect("register_project ToolDefinition");
        assert!(definition.model_spec.is_some());
        definition.model_spec = None;
        let _ = resolve_tool_specs(std::iter::once(&definition));
    }

    #[test]
    #[should_panic(expected = "register_project model-visible ToolDefinition is duplicated")]
    fn duplicate_definition_owned_model_specs_fail_closed() {
        let definition =
            *lookup_tool_definition("register_project").expect("register_project ToolDefinition");
        assert!(definition.model_spec.is_some());
        let duplicate = definition;
        let _ = resolve_tool_specs([&definition, &duplicate]);
    }

    #[test]
    fn reliability_tool_descriptions_are_selection_dense_and_keep_lifecycle_contracts() {
        let specs = registered_tool_specs();
        let find = |name: &str| {
            specs
                .iter()
                .find(|spec| spec.name == name)
                .unwrap_or_else(|| panic!("missing tool spec: {name}"))
        };

        for spec in &specs {
            assert!(
                spec.description.chars().count() <= crate::MODEL_TOOL_DESCRIPTION_MAX_CHARS,
                "{} description exceeds the hard model budget ({} > {} chars): {}",
                spec.name,
                spec.description.chars().count(),
                crate::MODEL_TOOL_DESCRIPTION_MAX_CHARS,
                spec.description
            );
        }

        for name in [
            "run_process",
            "run_script",
            "cargo_fmt",
            "cargo_check",
            "cargo_test",
            "go_test",
        ] {
            let description = &find(name).description;
            assert!(
                description.contains("same execution"),
                "{name}: {description}"
            );
            assert!(!description.contains("run_job"), "{name}: {description}");
        }
        assert!(find("run_process").description.contains("run_shell"));
        assert!(find("run_script").description.contains("run_shell"));
        for name in ["cargo_fmt", "cargo_check", "cargo_test", "go_test"] {
            let description = &find(name).description;
            assert!(!description.contains("run_shell"), "{name}: {description}");
        }

        let run_job = &find("run_job").description;
        assert!(run_job.contains("stable job_id"), "{run_job}");
        assert!(run_job.contains("observe"), "{run_job}");
        assert!(run_job.contains("retry"), "{run_job}");

        let observe_jobs = find("observe_jobs");
        let description = &observe_jobs.description;
        let lower = description.to_ascii_lowercase();
        assert!(lower.contains("never"), "observe_jobs: {description}");
        assert!(lower.contains("retr"), "observe_jobs: {description}");

        let token = observe_jobs.input_schema["properties"]["items"]["items"]["oneOf"][0]
            ["properties"]["after_observation_token"]["description"]
            .as_str()
            .expect("observe_jobs raw-selector observation token description");
        assert!(token.contains("not execution identity"), "{token}");
        assert!(token.contains("Server epoch"), "{token}");
        assert!(token.contains("without interpreting"), "{token}");
        assert!(token.contains("Return it unchanged"), "{token}");
        let wait = observe_jobs.input_schema["properties"]["wait_secs"]["description"]
            .as_str()
            .expect("observe_jobs wait description");
        assert!(wait.contains("one shared bounded wait"), "{wait}");
        assert!(
            wait.contains(
                &webcodex_core::runtime_contract::MAX_JOB_OBSERVATION_WAIT_SECS.to_string()
            ),
            "{wait}"
        );

        let register = find("register_project");
        assert!(
            register.description.contains("non-Git"),
            "{}",
            register.description
        );
        assert_eq!(
            register.input_schema["properties"]["path"]["description"].as_str(),
            Some("Existing absolute directory path on the Runner. Git is not required.")
        );
        let work_on_project = &find("work_on_project").description;
        assert!(work_on_project.contains("project or client_id+path"));
        assert!(work_on_project.contains("does not require Git"));
        assert!(work_on_project.contains("mode=worktree"));
        assert!(work_on_project.contains("exact Git base"));
        assert!(work_on_project.contains("Project authority"));
        for name in ["list_runners", "runtime_status"] {
            let description = &find(name).description;
            assert!(
                description.contains("shared Job concurrency"),
                "{name}: {description}"
            );
            assert!(
                description.contains("host_context"),
                "{name}: {description}"
            );
            assert!(description.contains("advisory"), "{name}: {description}");
            assert!(description.contains("authority"), "{name}: {description}");
        }

        for spec in &specs {
            if !matches!(
                spec.name.as_str(),
                "run_shell" | "run_process" | "run_script" | "session_shell_exec"
            ) {
                assert!(
                    !spec.description.contains("run_shell"),
                    "{} pollutes exact run_shell discovery: {}",
                    spec.name,
                    spec.description
                );
            }
            if spec.name != "run_job" {
                assert!(
                    !spec.description.contains("run_job"),
                    "{} pollutes exact run_job discovery: {}",
                    spec.name,
                    spec.description
                );
            }
            if spec.name != "work_on_project" {
                assert!(
                    !spec.description.contains("work_on_project"),
                    "{} pollutes exact work_on_project discovery: {}",
                    spec.name,
                    spec.description
                );
            }
        }

        for spec in &specs {
            let mut descriptions = Vec::new();
            collect_schema_descriptions(&spec.input_schema, &mut descriptions);
            collect_schema_descriptions(&spec.output_schema, &mut descriptions);
            for description in descriptions {
                if spec.name != "run_shell" {
                    assert!(
                        !description.contains("run_shell"),
                        "{} schema pollutes exact run_shell discovery: {description}",
                        spec.name
                    );
                }
                if spec.name != "run_job" {
                    assert!(
                        !description.contains("run_job"),
                        "{} schema pollutes exact run_job discovery: {description}",
                        spec.name
                    );
                }
                if spec.name != "work_on_project" {
                    assert!(
                        !description.contains("work_on_project"),
                        "{} schema pollutes exact work_on_project discovery: {description}",
                        spec.name
                    );
                }
            }
        }
    }

    #[test]
    fn tool_specs_unified_diff_field_rejects_codex_wrapper() {
        let specs = registered_tool_specs();
        let spec = specs
            .iter()
            .find(|spec| spec.name == "apply_unified_diff")
            .expect("missing apply_unified_diff spec");
        let description = spec.input_schema["properties"]["diff"]["description"]
            .as_str()
            .expect("missing unified diff description");
        let lower = description.to_lowercase();
        assert!(lower.contains("raw standard unified diff"), "{description}");
        assert!(
            description.contains("Codex apply_patch wrapper"),
            "{description}"
        );
        assert!(description.contains("*** Begin Patch"), "{description}");
    }
}
