#!/usr/bin/env python3
"""Prepare one clone-free Docker Server bootstrap for an immutable image digest."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

SERVER_IMAGE = "ghcr.io/yyjeqhc/webcodex-server"
BOOTSTRAP_ASSET = "webcodex-server-bootstrap.sh"
MATERIALIZED_COMPOSE = "webcodex-server-compose.yaml"
DEFAULT_IMAGE_MARKER = f"image: ${{WEBCODEX_SERVER_IMAGE:-{SERVER_IMAGE}:latest}}"
HEREDOC_MARKER = "__WEBCODEX_RELEASE_COMPOSE_EOF__"
MAX_SOURCE_BYTES = 256 * 1024
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")


def _read_text(path: Path) -> str:
    data = path.read_bytes()
    if len(data) > MAX_SOURCE_BYTES:
        raise ValueError(f"source file exceeds {MAX_SOURCE_BYTES} bytes: {path}")
    if b"\0" in data:
        raise ValueError(f"source file contains NUL: {path}")
    return data.decode("utf-8")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def render_bootstrap(*, compose: str, bootstrap: str, digest: str) -> str:
    if not DIGEST_RE.fullmatch(digest):
        raise ValueError(f"invalid server image digest: {digest!r}")
    if compose.count(DEFAULT_IMAGE_MARKER) != 1:
        raise ValueError("canonical compose image marker is missing or duplicated")
    if "\n    build:\n" in compose or "webcodex-runner" in compose:
        raise ValueError("canonical server compose unexpectedly contains build or Runner content")
    if HEREDOC_MARKER in compose:
        raise ValueError("canonical compose collides with the bootstrap heredoc marker")

    pinned = f"image: ${{WEBCODEX_SERVER_IMAGE:-{SERVER_IMAGE}@{digest}}}"
    compose = compose.replace(DEFAULT_IMAGE_MARKER, pinned, 1)

    required_bootstrap_markers = (
        "COMPOSE_FILE",
        "docker compose -f",
        "compose config --images",
    )
    if any(marker not in bootstrap for marker in required_bootstrap_markers):
        raise ValueError("bootstrap script does not support standalone compose resolution")
    if not bootstrap.startswith("#!/bin/sh\n"):
        raise ValueError("canonical bootstrap must start with #!/bin/sh")
    body = bootstrap.removeprefix("#!/bin/sh\n")

    prelude = f"""#!/bin/sh
# Generated by the reviewed WebCodex release-image workflow. The embedded
# Compose definition is pinned to one immutable multi-arch Server image digest.
set -eu

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <public-https-url>" >&2
    exit 2
fi
release_public_url=${{1%/}}
case "$release_public_url" in
    https://*) ;;
    *) echo "public URL must start with https://" >&2; exit 2 ;;
esac
release_origin=${{release_public_url#https://}}
case "$release_origin" in
    ""|*/*) echo "public URL must be an HTTPS origin without a path" >&2; exit 2 ;;
esac

if [ -e .env ]; then
    echo ".env already exists; refusing to modify this deployment" >&2
    exit 1
fi

compose_target={MATERIALIZED_COMPOSE}
compose_tmp=".{MATERIALIZED_COMPOSE}.$$.tmp"
cleanup_release_compose() {{ rm -f "$compose_tmp"; }}
trap cleanup_release_compose EXIT HUP INT TERM
umask 077
cat > "$compose_tmp" <<'{HEREDOC_MARKER}'
{compose.rstrip()}
{HEREDOC_MARKER}
if [ -e "$compose_target" ]; then
    if ! cmp -s "$compose_tmp" "$compose_target"; then
        echo "$compose_target already exists with different content; refusing to overwrite it" >&2
        exit 1
    fi
    rm -f "$compose_tmp"
else
    mv "$compose_tmp" "$compose_target"
fi
trap - EXIT HUP INT TERM
COMPOSE_FILE="$compose_target"
export COMPOSE_FILE

"""
    return prelude + body


def prepare_assets(
    *,
    compose_path: Path,
    bootstrap_path: Path,
    output_dir: Path,
    digest: str,
) -> dict[str, str]:
    rendered = render_bootstrap(
        compose=_read_text(compose_path),
        bootstrap=_read_text(bootstrap_path),
        digest=digest,
    ).encode("utf-8")
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / BOOTSTRAP_ASSET
    if path.exists():
        raise ValueError(f"refusing to overwrite deployment asset: {path}")
    path.write_bytes(rendered)
    return {BOOTSTRAP_ASSET: sha256_bytes(rendered)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compose", required=True, type=Path)
    parser.add_argument("--bootstrap", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--digest", required=True)
    parser.add_argument("--summary", type=Path)
    args = parser.parse_args()

    assets = prepare_assets(
        compose_path=args.compose,
        bootstrap_path=args.bootstrap,
        output_dir=args.output_dir,
        digest=args.digest,
    )
    summary = json.dumps({"assets": assets}, indent=2, sort_keys=True) + "\n"
    if args.summary is not None:
        if args.summary.exists():
            raise SystemExit(f"refusing to overwrite summary: {args.summary}")
        args.summary.write_text(summary, encoding="utf-8", newline="\n")
    print(summary, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
