//! Minimal project-readiness console.
//!
//! Serves the embedded console HTML/JS/CSS bundle at `/console`,
//! `/console/app.js`, and `/console/styles.css`. These are static assets with
//! no secrets; they are served **without** Bearer auth (exactly like
//! `/openapi.json`). Readiness data is fetched by the browser from
//! `POST /api/connector/readiness`, which still requires Bearer auth.
//!
//! The bundle is generated by `frontend/scripts/build.mjs` from
//! `frontend/src/{console.html,app.ts,styles.css}` and is embedded into the
//! binary at compile time via `include_str!` so the deployed server is fully
//! self-contained. `npm run check:dist` guards against drift between the
//! TypeScript sources and the committed `frontend/dist/` outputs.
//!
//! The host-local review surface uses authenticated `POST /api/console/*`
//! operations. Its project credential remains in page memory only.

use salvo::http::header::CONTENT_TYPE;
use salvo::http::HeaderValue;
use salvo::prelude::*;

// The built bundle is committed under `frontend/dist/` and embedded at compile
// time so the binary has zero runtime file-system dependency. If these paths
// fail to resolve, run `npm --prefix frontend run build` first.
const CONSOLE_HTML: &str = include_str!("../frontend/dist/console.html");
const CONSOLE_APP_JS: &str = include_str!("../frontend/dist/app.js");
const CONSOLE_STYLES_CSS: &str = include_str!("../frontend/dist/styles.css");

/// `GET /console` — the console HTML shell. Public (no auth); data is fetched
/// by the page from the protected `POST /api/connector/readiness` endpoint.
#[handler]
pub async fn console_html(res: &mut Response) {
    res.render(Text::Html(CONSOLE_HTML));
}

/// `GET /console/app.js` — the console application script. Public.
#[handler]
pub async fn console_app_js(res: &mut Response) {
    res.render(Text::Plain(CONSOLE_APP_JS));
    // `Text::Plain` sets `text/plain`; override with the correct JS MIME type
    // so strict MIME-checking browsers accept it as a module-free script.
    res.headers_mut().insert(
        CONTENT_TYPE,
        HeaderValue::from_static("application/javascript; charset=utf-8"),
    );
}

/// `GET /console/styles.css` — the console stylesheet. Public.
#[handler]
pub async fn console_styles_css(res: &mut Response) {
    res.render(Text::Plain(CONSOLE_STYLES_CSS));
    res.headers_mut().insert(
        CONTENT_TYPE,
        HeaderValue::from_static("text/css; charset=utf-8"),
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use salvo::test::{ResponseExt, TestClient};
    use salvo::Service;
    use std::path::PathBuf;
    use std::sync::Arc;

    fn test_config(token: Option<&str>) -> Arc<crate::Config> {
        Arc::new(crate::Config {
            addr: "127.0.0.1:0".to_string(),
            data_dir: PathBuf::from("./data"),
            token: token.map(str::to_string),
            max_text_size: 2 * 1024 * 1024,
            max_file_size: 100 * 1024 * 1024,
            codex: crate::CodexConfig::default(),
            oauth2: crate::OAuth2Config::default(),
        })
    }

    /// Create an empty Database in a temp dir. The TempDir must be kept alive
    /// for the lifetime of the returned Database so the sqlite file is not
    /// deleted mid-test.
    fn test_db() -> (tempfile::TempDir, Arc<crate::Database>) {
        let tmp = tempfile::tempdir().unwrap();
        let db = crate::Database::open(&tmp.path().join("test.db")).unwrap();
        (tmp, Arc::new(db))
    }

    /// Build a router that mirrors the production `/console` wiring (public,
    /// no AuthMiddleware) plus the protected Connector readiness route
    /// route so tests can assert both the public console entry and that the
    /// data API still requires Bearer auth.
    fn build_test_router(config: Arc<crate::Config>, db: Arc<crate::Database>) -> Router {
        let shell_registry = Arc::new(crate::ShellClientRegistry::default());
        let runtime_info = Arc::new(crate::tool_runtime::RuntimeInfo::default());
        let tool_runtime = Arc::new(crate::tool_runtime::ToolRuntime::new(
            shell_registry,
            Arc::new(config.codex.clone()),
            runtime_info,
        ));
        Router::new()
            .hoop(affix_state::inject(config))
            .hoop(affix_state::inject(db))
            .hoop(affix_state::inject(tool_runtime))
            .hoop(affix_state::inject(
                crate::connector_runtime::ConnectorRuntimeSlot::default(),
            ))
            .push(Router::with_path("console").get(console_html))
            .push(Router::with_path("console/app.js").get(console_app_js))
            .push(Router::with_path("console/styles.css").get(console_styles_css))
            .push(
                Router::with_path("api")
                    .hoop(crate::AuthMiddleware)
                    .push(crate::connector_runtime::http::routes()),
            )
    }

    fn content_type(resp: &Response) -> String {
        resp.headers()
            .get(CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_string()
    }

    #[test]
    fn embedded_bundle_is_non_empty_and_has_expected_markers() {
        // HTML shell must reference the JS/CSS assets and declare a root node.
        assert!(!CONSOLE_HTML.is_empty());
        assert!(CONSOLE_HTML.contains("/console/app.js"));
        assert!(CONSOLE_HTML.contains("/console/styles.css"));
        assert!(CONSOLE_APP_JS.contains("/api/console/"));
        assert!(!CONSOLE_APP_JS.contains("/api/runtime/status"));
        assert!(!CONSOLE_APP_JS.contains("localStorage"));
        assert!(!CONSOLE_APP_JS.contains("sessionStorage"));
        assert!(!CONSOLE_APP_JS.contains(".innerHTML"));
        assert!(CONSOLE_APP_JS.contains("performAction"));
        assert!(CONSOLE_HTML.contains("type=\"password\""));
        assert!(!CONSOLE_HTML.contains("Transport"));
    }

    #[tokio::test]
    async fn http_console_html_is_public_and_serves_html() {
        let config = test_config(Some("secret"));
        let (_tmp, db) = test_db();
        let service = Service::new(build_test_router(config, db));
        let resp = TestClient::get("http://localhost/console")
            .send(&service)
            .await;
        assert_eq!(resp.status_code.unwrap_or(StatusCode::OK), StatusCode::OK);
        assert!(content_type(&resp).contains("text/html"));
    }

    #[tokio::test]
    async fn http_console_app_js_has_javascript_mime() {
        let config = test_config(Some("secret"));
        let (_tmp, db) = test_db();
        let service = Service::new(build_test_router(config, db));
        let resp = TestClient::get("http://localhost/console/app.js")
            .send(&service)
            .await;
        assert_eq!(resp.status_code.unwrap_or(StatusCode::OK), StatusCode::OK);
        assert!(content_type(&resp).contains("javascript"));
    }

    #[tokio::test]
    async fn http_console_styles_css_has_css_mime() {
        let config = test_config(Some("secret"));
        let (_tmp, db) = test_db();
        let service = Service::new(build_test_router(config, db));
        let resp = TestClient::get("http://localhost/console/styles.css")
            .send(&service)
            .await;
        assert_eq!(resp.status_code.unwrap_or(StatusCode::OK), StatusCode::OK);
        assert!(content_type(&resp).contains("text/css"));
    }

    #[tokio::test]
    async fn http_readiness_requires_bearer_auth() {
        // The console page is public, but the data API it calls must still
        // reject requests without a Bearer token.
        let config = test_config(Some("secret"));
        let (_tmp, db) = test_db();
        let service = Service::new(build_test_router(config, db));
        let resp = TestClient::post("http://localhost/api/connector/readiness")
            .json(&serde_json::json!({}))
            .send(&service)
            .await;
        assert_eq!(
            resp.status_code.unwrap_or(StatusCode::OK),
            StatusCode::UNAUTHORIZED
        );
    }

    #[tokio::test]
    async fn http_readiness_projects_setup_action_with_bearer_auth() {
        let config = test_config(Some("secret"));
        let (_tmp, db) = test_db();
        let service = Service::new(build_test_router(config, db));
        let mut resp = TestClient::post("http://localhost/api/connector/readiness")
            .bearer_auth("secret")
            .json(&serde_json::json!({}))
            .send(&service)
            .await;
        assert_eq!(
            resp.status_code.unwrap_or(StatusCode::OK),
            StatusCode::NOT_FOUND
        );
        let body: serde_json::Value = resp.take_json().await.unwrap();
        assert_eq!(body["ready"], false);
        assert_eq!(body["findings"][1]["code"], "project_registration_invalid");
        assert_eq!(body["next_action"], "webcodex doctor");
    }
}
