use super::RunnerCapabilityRequirement::{FileRead, FileWrite};
use super::ToolVisibility::ModelVisible;
use super::{
    adaptive_runtime_direct, def, model_spec, permission_risk,
    requires_artifact_upload_path_binding, ToolDefinition, PERMISSION_RISK_ARTIFACT_WRITE,
    TOOL_CATEGORY_ARTIFACT,
};
use crate::metadata::{
    ToolPathHint::Artifact,
    ToolRisk::{ProjectWrite, Read},
    PROJECT_READ, PROJECT_WRITE, TOOL_PROVIDER_CONTROL, TOOL_PROVIDER_RUNNER,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    permission_risk(
        model_spec(
            def(
            "save_project_artifact",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileWrite),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            Artifact,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE,
            ),
            "Write a bounded binary project artifact when the caller already holds the bounded binary/base64 content. Do not read a current ChatGPT/host attachment and base64-encode it through the model; use import_conversation_files_to_project for host-native attachment import. Suitable for generated images, PDFs, ZIP archives, and DOCX/PPTX/XLSX Office artifacts already present as bounded caller data; not for UTF-8 source edits.",
        ),
        PERMISSION_RISK_ARTIFACT_WRITE,
    ),
    adaptive_runtime_direct(
        permission_risk(
            model_spec(
                def(
                    "import_conversation_files_to_project",
                    super::ToolAuditPolicy::TYPED_CANONICAL,
                    ModelVisible,
                    TOOL_CATEGORY_ARTIFACT,
                    Some(FileWrite),
                    TOOL_PROVIDER_CONTROL,
                    super::ToolSemanticContract {
                        effect: super::ToolEffect::Mutate,
                        risk: ProjectWrite,
                        approval: super::ToolApprovalPolicy::Standard,
                        idempotency: super::ToolIdempotency::NonIdempotent,
                    },
                    Some(PROJECT_WRITE),
                    true,
                    Artifact,
                    true,
                    false,
                    super::ToolSessionEvidencePolicy::NONE,
                ),
                "Import 1..10 current ChatGPT/host attachments into a Runner project using openaiFileIdRefs from the host file-reference mechanism. This is the preferred host-native attachment-to-project transfer path: do not base64-transfer files, construct download URLs, or use local /mnt/data paths; Control downloads and saves them as project artifacts. Existing trusted MCP host/OAuth client and host rewrite checks still apply.",
            ).with_gpt_action_description("Import current ChatGPT attachments into a Runner project through host-populated openaiFileIdRefs. Do not invent file ids/URLs or base64-transfer attachments. Host provenance is adapter-derived; runtime authority remains canonical."),
            PERMISSION_RISK_ARTIFACT_WRITE,
        ),
        55,
    ),
    adaptive_runtime_direct(
        model_spec(
            def(
                "project_artifact",
                super::ToolAuditPolicy::TYPED_CANONICAL,
                ModelVisible,
                TOOL_CATEGORY_ARTIFACT,
                Some(FileRead),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(PROJECT_READ),
                true,
                Artifact,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Project artifact read: metadata=facts; inspect=fenced segment; image=MCP image; export=MCP ResourceLink. Use export for whole files, not repeated inspect calls; use import_conversation_files_to_project for host-to-Project attachments.",
        )
        .with_gpt_action_description("Project artifact read surface. GPT Actions supports metadata and bounded inspect; native image and ResourceLink export require MCP."),
        56,
    ),
    model_spec(
        def(
            "export_project_artifact",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileRead),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            Artifact,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Compatibility project artifact export specialist. Create one short-lived authenticated MCP ResourceLink for a bounded project artifact so the host/user can fetch the complete binary with resources/read without routing base64 through model output. Prefer project_artifact(action=export) on model surfaces that expose the unified facade.",
    )
    .with_gpt_action_unsupported(),
    model_spec(
        def(
            "project_artifact_download_link",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("project"),
                super::ToolAuditResultField::value("path"),
                super::ToolAuditResultField::value("download_url"),
                super::ToolAuditResultField::value("expires_in_secs"),
                super::ToolAuditResultField::value("bytes"),
                super::ToolAuditResultField::value("sha256"),
                super::ToolAuditResultField::value("mime_type"),
                super::ToolAuditResultField::value("name"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileRead),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_READ),
            true,
            Artifact,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Issue one short-lived one-shot HTTPS download link for an exact bounded project artifact. The URL carries only an opaque capability id; project path and credentials are never embedded. Use this after computer_save_display_snapshot when GPT Actions must retrieve the complete image without base64 in Action JSON.",
    ),
    model_spec(
        def(
            "read_project_artifact_metadata",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileRead),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            Artifact,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Read bounded metadata for a binary artifact; images include dimensions and zip archives are counted but never extracted. Set allow_missing=true to make a missing artifact a successful exists=false negative assertion.",
    ),
    model_spec(
        def(
            "read_project_artifact",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileRead),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            Artifact,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Bounded chunk inspection API for a project artifact. Returns base64 for one small segment plus full-file sha256/MIME metadata. A truncated ranged read emits one parser-ready suggested_call that carries the observed full-file sha256 as expected_sha256, so continuation either reads the same exact content incarnation or fails closed with snapshot_changed before returning changed bytes; do not manually translate next_offset or sha256 bookkeeping. If the goal is to deliver the complete file to ChatGPT/host/user, do not loop over base64 chunks; prefer export_project_artifact instead.",
    ),
    model_spec(
        def(
            "artifact_upload_begin",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileWrite),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            Artifact,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Begin a bounded low-level chunked binary artifact upload up to 256 MiB. Creates a project-local temporary upload session; finish commits atomically to the target path. This is not the preferred path for a current ChatGPT/host attachment; use import_conversation_files_to_project for host-native import. For smoke octet-stream uploads, use artifacts/smoke/<name>.artifact or omit mime_type when appropriate.",
    ),
    requires_artifact_upload_path_binding(model_spec(
        def(
            "artifact_upload_chunk",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileWrite),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            Artifact,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Append one base64 chunk up to 1 MiB decoded to an active artifact upload. path is required and must exactly match artifact_upload_begin; this binds upload_id to the target path.",
    )),
    requires_artifact_upload_path_binding(permission_risk(
        model_spec(
            def(
            "artifact_upload_finish",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileWrite),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            Artifact,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE,
            ),
            "Finish an active artifact upload. path is required and must exactly match artifact_upload_begin; this binds upload_id before atomic commit.",
        ),
        PERMISSION_RISK_ARTIFACT_WRITE,
    )),
    requires_artifact_upload_path_binding(permission_risk(
        model_spec(
            def(
            "artifact_upload_abort",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_ARTIFACT,
            Some(FileWrite),
            TOOL_PROVIDER_RUNNER,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            Artifact,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE,
            ),
            "Abort an active artifact upload. path is required and must exactly match artifact_upload_begin; this binds upload_id before cleanup and reports final_file_exists without touching the final target.",
        ),
        PERMISSION_RISK_ARTIFACT_WRITE,
    )),
];
