use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, permission_risk, require_all_scopes, ToolDefinition,
    PERMISSION_RISK_WRITE, TOOL_CATEGORY_COMMUNICATION,
};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{CommunicationManage, Read},
    COMMUNICATION_MANAGE, COMMUNICATION_READ, TOOL_PROVIDER_CONTROL,
};
use webcodex_core::authority::{COMMUNICATION_MANAGE_SCOPES, COMMUNICATION_READ_SCOPES};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        model_spec(
            def(
                "create_agent_identity",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent/agent_id"),
                    super::ToolAuditResultField::pointer("profile_revision", "/agent/profile_revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Create a durable Server-owned Agent identity and mutable self-description card. For a new ChatGPT window that needs durable Agent continuation, this is the first setup step; next use rotate_agent_continuation_endpoint, then present_agent_continuation. The canonical wc_dagent_* id remains independent from windows, Endpoints, Workflow Sessions, Projects, and execution authority. Exact idempotency-key replay returns the original Agent; changed reuse is rejected.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_agent_identities",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("total_count"),
                    super::ToolAuditResultField::array_len("returned_count", "agents"),
                    super::ToolAuditResultField::value("offset"),
                    super::ToolAuditResultField::value("next_offset"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "List bounded durable Agent cards owned by the current communication principal, or read one exact Agent. Each listed Agent includes production_auto_resume_available, a read-only conjunction of current durable Endpoint truth and the current Server process's production Host carrier for that exact generation. It is continuation readiness only: not idle/presence, not a capacity reservation, not execution authority, and not a guarantee of immediate Host scheduling. Handles, names, descriptions, labels, and Endpoint counts are metadata only and never grant Project, filesystem, Runner, or Workflow Session authority.",
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "update_agent_identity",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent/agent_id"),
                    super::ToolAuditResultField::pointer("profile_revision", "/agent/profile_revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Update an owned Agent Card behind expected_profile_revision. Canonical agent_id never changes, and handle/display-name collisions remain allowed. On uncertain outcome, re-read the Agent instead of changing the revision fence blindly.",
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        adaptive_runtime_direct(
            permission_risk(
                model_spec(
                    def(
                        "rotate_agent_continuation_endpoint",
                        super::ToolAuditPolicy::typed_fields(&[
                            super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                            super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                            super::ToolAuditResultField::pointer_non_null("detached", "/endpoint/detached_at_unix_ms"),
                            super::ToolAuditResultField::value("created"),
                            super::ToolAuditResultField::value("replayed"),
                            super::ToolAuditResultField::value("state_changed"),
                            super::ToolAuditResultField::value("error_kind"),
                        ])
                        .context(super::ToolAuditContextPolicy::Fields(&[
                            super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                            super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                            super::ToolAuditResultField::value("created"),
                            super::ToolAuditResultField::value("replayed"),
                            super::ToolAuditResultField::value("state_changed"),
                            super::ToolAuditResultField::value("error_kind"),
                        ])),
                        ModelVisible,
                        TOOL_CATEGORY_COMMUNICATION,
                        None,
                        TOOL_PROVIDER_CONTROL,
                        super::ToolSemanticContract {
                            effect: super::ToolEffect::Mutate,
                            risk: CommunicationManage,
                            approval: super::ToolApprovalPolicy::Standard,
                            idempotency: super::ToolIdempotency::Keyed,
                        },
                        Some(COMMUNICATION_MANAGE),
                        false,
                        NoPath,
                        true,
                        false,
                        super::ToolSessionEvidencePolicy::NONE,
                    ),
                    "Create or rotate the server-local continuation Endpoint for an owned durable Agent. This is the canonical Endpoint step for first-time durable continuation setup; later calls replace the Endpoint with a new monotonic controller generation and make older generations stale. Next usually call present_agent_continuation. This tool does not establish a Host binding or production auto-resume readiness. Exact idempotency replay returns the same Endpoint.",
                ),
                PERMISSION_RISK_WRITE,
            )
            .with_gpt_action_unsupported(),
            19,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "attach_agent_endpoint",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                    super::ToolAuditResultField::pointer_non_null("detached", "/endpoint/detached_at_unix_ms"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context(super::ToolAuditContextPolicy::Fields(&[
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Compatibility name for rotate_agent_continuation_endpoint. Rotates only the server-local continuation Endpoint record for an owned durable Agent, assigns a new monotonic controller generation, and makes older generations stale. It does not connect to, configure, or control ChatGPT or any external Host. Public rotation is not wake-capable until a separately authorized process-local Host binding is established. Exact idempotency replay returns the same Endpoint.",
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        adaptive_runtime_direct(
            model_spec(
                def(
                    "present_agent_continuation",
                    super::ToolAuditPolicy::typed_fields(&[
                        super::ToolAuditResultField::pointer("agent_id", "/agent_continuation/agent_id"),
                        super::ToolAuditResultField::pointer("endpoint_id", "/agent_continuation/endpoint_id"),
                        super::ToolAuditResultField::pointer("controller_generation", "/agent_continuation/controller_generation"),
                        super::ToolAuditResultField::pointer("wake_id", "/agent_continuation/wake/wake_id"),
                        super::ToolAuditResultField::pointer("wake_state", "/agent_continuation/wake/state"),
                        super::ToolAuditResultField::pointer("queued_delivery_count", "/agent_continuation/queued_delivery_count"),
                        super::ToolAuditResultField::pointer("dispatch_observation", "/agent_continuation/dispatch_observation"),
                        super::ToolAuditResultField::value("error_kind"),
                    ]),
                    ModelVisible,
                    TOOL_CATEGORY_COMMUNICATION,
                    None,
                    TOOL_PROVIDER_CONTROL,
                    super::ToolSemanticContract {
                        effect: super::ToolEffect::Observe,
                        risk: Read,
                        approval: super::ToolApprovalPolicy::None,
                        idempotency: super::ToolIdempotency::PureRead,
                    },
                    Some(COMMUNICATION_READ),
                    false,
                    NoPath,
                    false,
                    false,
                    super::ToolSessionEvidencePolicy::NONE,
                ),
                "Present one explicit durable Agent/Endpoint generation as a sparse MCP App continuation controller card. New durable Agent window setup is create_agent_identity -> rotate_agent_continuation_endpoint -> present_agent_continuation; after presentation, yield/end the current model turn promptly so the MCP App can establish and maintain the Host binding. Presentation success is not production auto-resume readiness: verify list_agent_identities.production_auto_resume_available afterward. All identity fields remain explicit; presentation is read-only and never itself establishes Host binding or execution authority.",
            )
            .with_gpt_action_unsupported(),
            18,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_bind",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent_continuation/agent_id"),
                    super::ToolAuditResultField::pointer("endpoint_id", "/agent_continuation/endpoint_id"),
                    super::ToolAuditResultField::pointer("controller_generation", "/agent_continuation/controller_generation"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_recover_endpoint",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent_continuation/agent_id"),
                    super::ToolAuditResultField::pointer("endpoint_id", "/agent_continuation/endpoint_id"),
                    super::ToolAuditResultField::pointer("controller_generation", "/agent_continuation/controller_generation"),
                    super::ToolAuditResultField::pointer("recovery_kind", "/endpoint_recovery/kind"),
                    super::ToolAuditResultField::pointer("from_endpoint_id", "/endpoint_recovery/replacement/from_endpoint_id"),
                    super::ToolAuditResultField::pointer("from_controller_generation", "/endpoint_recovery/replacement/from_controller_generation"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_state",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/agent_continuation/agent_id"),
                    super::ToolAuditResultField::pointer("endpoint_id", "/agent_continuation/endpoint_id"),
                    super::ToolAuditResultField::pointer("controller_generation", "/agent_continuation/controller_generation"),
                    super::ToolAuditResultField::pointer("wake_id", "/agent_continuation/wake/wake_id"),
                    super::ToolAuditResultField::pointer("wake_state", "/agent_continuation/wake/state"),
                    super::ToolAuditResultField::pointer("dispatch_observation", "/agent_continuation/dispatch_observation"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_wake_acquire",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::value("endpoint_id"),
                    super::ToolAuditResultField::pointer("wake_id", "/wake/wake_id"),
                    super::ToolAuditResultField::pointer("attempt_id", "/wake/attempt_id"),
                    super::ToolAuditResultField::pointer("wake_state", "/wake/state"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_wake_prepare",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::value("endpoint_id"),
                    super::ToolAuditResultField::value("wake_id"),
                    super::ToolAuditResultField::value("attempt_id"),
                    super::ToolAuditResultField::value("wake_revision"),
                    super::ToolAuditResultField::value("dispatch_observation"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_wake_finish",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::value("endpoint_id"),
                    super::ToolAuditResultField::value("wake_id"),
                    super::ToolAuditResultField::value("attempt_id"),
                    super::ToolAuditResultField::value("wake_state"),
                    super::ToolAuditResultField::value("wake_revision"),
                    super::ToolAuditResultField::value("dispatch_observation"),
                    super::ToolAuditResultField::value("continuation_consumed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            def(
                "agent_continuation_unbind",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::value("endpoint_id"),
                    super::ToolAuditResultField::value("controller_generation"),
                    super::ToolAuditResultField::value("wake_capable"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelHidden,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "bootstrap_agent_conversation",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("agent_id", "/acting_agent/agent_id"),
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("controller_generation", "/endpoint/controller_generation"),
                    super::ToolAuditResultField::pointer("conversation_id", "/selected_conversation/conversation_id"),
                    super::ToolAuditResultField::pointer("queued_delivery_count", "/inbox/queued_delivery_count"),
                    super::ToolAuditResultField::pointer("wake_id", "/wake/wake_id"),
                    super::ToolAuditResultField::pointer("wake_state", "/wake/state"),
                    super::ToolAuditResultField::pointer("adapter_kind", "/host_binding/adapter_kind"),
                    super::ToolAuditResultField::pointer("runtime_wake_capable", "/host_binding/runtime_wake_capable"),
                    super::ToolAuditResultField::pointer("production_auto_resume_available", "/host_binding/production_auto_resume_available"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            "Verify an exact Agent/Endpoint generation and return bounded turn context without Message bodies. activation_idempotency_key is only for explicit activation of an eligible pending Inbox-style Wake into this already-active turn; omit it for agent_task_attempt, attention_event, and agent_wait_events Wakes already dispatched by an Endpoint carrier. Explicit activation never requests a new model turn.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "detach_agent_endpoint",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                    super::ToolAuditResultField::pointer_non_null("detached", "/endpoint/detached_at_unix_ms"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context(super::ToolAuditContextPolicy::Fields(&[
                    super::ToolAuditResultField::pointer("endpoint_id", "/endpoint/endpoint_id"),
                    super::ToolAuditResultField::pointer("agent_id", "/endpoint/agent_id"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Detach a principal-bound Agent Endpoint without deleting the durable Agent, Conversation transcript, or Inbox. Repeating the same detach is a safe desired-state retry; a new Endpoint may later attach the same agent_id.",
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "create_conversation",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("conversation_id", "/conversation/conversation/conversation_id"),
                    super::ToolAuditResultField::pointer_array_len("participant_count", "/conversation/participants"),
                    super::ToolAuditResultField::pointer_array_len("message_count", "/conversation/messages"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context(super::ToolAuditContextPolicy::Fields(&[
                    super::ToolAuditResultField::pointer(
                        "conversation_id",
                        "/conversation/conversation/conversation_id",
                    ),
                    super::ToolAuditResultField::pointer_array_len(
                        "participant_count",
                        "/conversation/participants",
                    ),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Create a durable Conversation containing the current Human principal and one or more owned Agents. Participation authorizes communication only, never Project, filesystem, Runner, Task, or Workflow Session execution. Exact idempotency-key replay returns the original Conversation.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_conversations",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("total_count"),
                    super::ToolAuditResultField::array_len("returned_count", "conversations"),
                    super::ToolAuditResultField::value("offset"),
                    super::ToolAuditResultField::value("next_offset"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "List bounded Conversations visible to the current Human principal, or to an Agent proven by an active principal-bound Endpoint. Agent views include queued-delivery counts; listing never consumes Inbox state or invokes a model.",
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "read_conversation",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("conversation_id", "/conversation/conversation_id"),
                    super::ToolAuditResultField::array_len("participant_count", "participants"),
                    super::ToolAuditResultField::array_len("message_count", "messages"),
                    super::ToolAuditResultField::value("after_seq"),
                    super::ToolAuditResultField::value("next_after_seq"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Read a bounded ordered page from an append-only durable Conversation transcript, with participant and author provenance. Use after_seq for deterministic continuation. Reading does not consume recipient-specific Inbox deliveries or wake a model.",
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "post_conversation_message",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("message_id", "/message/message_id"),
                    super::ToolAuditResultField::pointer("conversation_id", "/message/conversation_id"),
                    super::ToolAuditResultField::pointer("seq", "/message/seq"),
                    super::ToolAuditResultField::pointer_array_len("delivery_count", "/message/deliveries"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Atomically append one Message, recipient Deliveries, and a coalesced Wake. Exact replay cannot duplicate them; Agent authors require the current Endpoint generation. After commit, a registered exact Host adapter may receive one bounded continuation; otherwise the Wake stays pending.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_agent_inbox",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::value("total_queued_count"),
                    super::ToolAuditResultField::array_len("returned_count", "deliveries"),
                    super::ToolAuditResultField::value("after_delivery_order"),
                    super::ToolAuditResultField::value("next_after_delivery_order"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "List queued recipient-specific deliveries for an Agent proven by an active principal-bound Endpoint. Use after_delivery_order for bounded continuation. Offline Agents retain deliveries; reading does not consume them or invoke a model.",
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "consume_agent_deliveries",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("agent_id"),
                    super::ToolAuditResultField::array_len("consumed_count", "consumed_delivery_ids"),
                    super::ToolAuditResultField::array_len("already_consumed_count", "already_consumed_delivery_ids"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::DesiredState,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Mark exact deliveries consumed in an Agent Inbox proven by an active principal-bound Endpoint. This mutates recipient state only, never the append-only Message or Wake state. Repeating already-consumed ids is a safe desired-state retry.",
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        permission_risk(
            model_spec(
            def(
                "consume_agent_wake",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("wake_id"),
                    super::ToolAuditResultField::value("target_agent_id"),
                    super::ToolAuditResultField::value("state"),
                    super::ToolAuditResultField::value("already_consumed"),
                    super::ToolAuditResultField::value("consumed_at_unix_ms"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ])
                .context_from_result(),
                ModelVisible,
                TOOL_CATEGORY_COMMUNICATION,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: CommunicationManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::FencedReplay,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                true,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            "Consume one exact durable Agent Wake continuation after accepting the resumed model turn. wake_id and consume_token identify the exact continuation, while endpoint_id and expected_controller_generation fence stale attachments. Repeating the same exact consume returns already_consumed without another state change. This operation never consumes Agent Inbox deliveries and grants no Project, filesystem, Runner, Task, or Workflow Session authority.",
            ),
            PERMISSION_RISK_WRITE,
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
];
