use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, require_all_scopes, ToolDefinition,
    TOOL_CATEGORY_GOAL,
};
use crate::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{Read, WorkflowManage},
    COMMUNICATION_MANAGE, COMMUNICATION_READ, TOOL_PROVIDER_CONTROL,
};
use webcodex_core::authority::{
    COMMUNICATION_MANAGE_SCOPES, COMMUNICATION_READ_SCOPES, SCOPE_COMMUNICATION_MANAGE,
    SCOPE_COMMUNICATION_READ, SCOPE_PROJECT_READ, SCOPE_RUNTIME_READ, SCOPE_SESSION_COLLABORATE,
};

const GOAL_SESSION_ASSOCIATE_SCOPES: &[&str] = &[
    SCOPE_COMMUNICATION_READ,
    SCOPE_COMMUNICATION_MANAGE,
    SCOPE_SESSION_COLLABORATE,
];

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        model_spec(
            def(
                "prepare_goal_workflow",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("lifecycle", "/goal/summary/lifecycle"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::pointer(
                        "workflow_session_count",
                        "/goal/summary/workflow_session_count",
                    ),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: WorkflowManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Atomically admit one new durable Goal together with one exact independently authorized Workflow Session correlation and an optional explicit owned controller Agent. The Store commits Goal + correlation + keyed replay identity in one transaction at revision 1. This operation is Host-neutral: it never infers identity from a Window, creates/rotates Endpoints, mounts MCP Apps, establishes Host bindings, creates Wakes, or proves continuation readiness. Use present_goal_plan separately; if automatic continuation is desired, independently establish or verify the controller through the agent_continuation_setup flow.",
        ),
        GOAL_SESSION_ASSOCIATE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "create_goal",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("lifecycle", "/goal/summary/lifecycle"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: WorkflowManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Create a durable Goal with fixed bounded completion intent and plan for substantial multi-step or cross-turn work; reuse an existing Goal when appropriate. Tiny lookups/trivial edits do not need one. Explicitly associate the current Workflow Session, then checkpoint recovery-worthy milestones. For automatic continuation supply an exact owned controller Agent and use the existing continuation carrier. Reuse an already-callable Agent from explicit durable setup or exact Wake context, never from Window inference. Controller identity routes attention only and grants no execution authority.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "get_goal",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("lifecycle", "/goal/summary/lifecycle"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Read one exact caller-owned durable Goal, including its optional durable controller Agent identity. Unauthorized and nonexistent Goal ids are existence-hidden. Controller/correlation identities are routing or correlation only and never target-domain authority, Endpoint/window bindings, fences, tokens, credentials, Job state, or Workflow Session ledgers.",
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        adaptive_runtime_direct(
            model_spec(
                def(
                    "present_goal_plan",
                    super::ToolAuditPolicy::typed_fields(&[
                        super::ToolAuditResultField::pointer("goal_id", "/goal_plan/goal_id"),
                        super::ToolAuditResultField::pointer("lifecycle", "/goal_plan/lifecycle"),
                        super::ToolAuditResultField::pointer("revision", "/goal_plan/revision"),
                        super::ToolAuditResultField::pointer(
                            "agent_task_count",
                            "/goal_plan/agent_task_count",
                        ),
                        super::ToolAuditResultField::pointer(
                            "workflow_session_count",
                            "/goal_plan/workflow_session_count",
                        ),
                        super::ToolAuditResultField::value("error_kind"),
                    ]),
                    ModelVisible,
                    TOOL_CATEGORY_GOAL,
                    None,
                    TOOL_PROVIDER_CONTROL,
                    super::ToolSemanticContract {
                        effect: super::ToolEffect::Observe,
                        risk: Read,
                        approval: super::ToolApprovalPolicy::None,
                        idempotency: super::ToolIdempotency::PureRead,
                    },
                    Some(COMMUNICATION_READ),
                    false,
                    NoPath,
                    false,
                    false,
                    super::ToolSessionEvidencePolicy::NONE,
                ),
                "Present one exact caller-owned durable Goal as a sparse read-only Goal Plan MCP App card, including only the optional durable controller Agent identity and never its Endpoint/window bindings. Requires explicit goal_id and never infers Goal or controller identity from Project, Workflow Session, Conversation, credential, ClientWindow, or recent activity. Presentation creates no work, grants no execution authority, and does not modify Goal lifecycle.",
            )
            .with_gpt_action_unsupported(),
            17,
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        def(
            "goal_plan_sync",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::pointer("goal_id", "/goal_plan/goal_id"),
                super::ToolAuditResultField::pointer("lifecycle", "/goal_plan/lifecycle"),
                super::ToolAuditResultField::pointer("revision", "/goal_plan/revision"),
                super::ToolAuditResultField::pointer(
                    "agent_task_count",
                    "/goal_plan/agent_task_count",
                ),
                super::ToolAuditResultField::pointer(
                    "workflow_session_count",
                    "/goal_plan/workflow_session_count",
                ),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelHidden,
            TOOL_CATEGORY_GOAL,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: WorkflowManage,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(COMMUNICATION_MANAGE),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Transport,
            super::ToolActivityInteraction::NonMeaningful,
        ),
        &[SCOPE_COMMUNICATION_READ, SCOPE_COMMUNICATION_MANAGE, SCOPE_RUNTIME_READ, SCOPE_SESSION_COLLABORATE, SCOPE_PROJECT_READ],
    ),
    require_all_scopes(
        model_spec(
            def(
                "list_goals",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("total_count"),
                    super::ToolAuditResultField::array_len("returned_count", "goals"),
                    super::ToolAuditResultField::value("offset"),
                    super::ToolAuditResultField::value("next_offset"),
                    super::ToolAuditResultField::value("truncated"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMMUNICATION_READ),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "List bounded Goals visible to the current owner principal, optionally filtered by authoritative lifecycle. List projection omits objective, terminal reason, and exact correlation identities.",
        ),
        COMMUNICATION_READ_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "checkpoint_goal",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("lifecycle", "/goal/summary/lifecycle"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: WorkflowManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Checkpoint one exact owned active Goal at a recovery-worthy milestone. Atomically complete selected stable step ids, optionally select one current step, and record a bounded summary using the exact revision and idempotency key. The whole batch validates before mutation; completed steps never regress, at most one step is in_progress, and each new checkpoint increments revision once. Exact replay is read-only; changed replay conflicts. Terminal Goals are immutable. This is progress truth, not effect replay, execution authority, or a routine session_handoff_summary requirement.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "update_goal",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("lifecycle", "/goal/summary/lifecycle"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::value("created"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: WorkflowManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Update bounded Goal metadata, explicitly replace its exact independently authorized durable controller Agent, or transition active to completed/cancelled using an exact revision and idempotency key. Omitted controller preserves the current routing identity; terminal Goal state is immutable. Controller routing grants no execution authority and no execution domain is inferred or mutated. Complete every plan step with checkpoint_goal and freshly verify/review before explicitly completing a Goal; the Server cannot judge natural-language completion conditions.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "associate_goal_agent_task",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: WorkflowManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Explicitly correlate one owned active Goal with one exact owned AgentTask after independently re-authorizing that AgentTask. The link is identity-only and grants no TaskAttempt, CodingAgentRun, Project, Runner, filesystem, or Job authority.",
        ),
        COMMUNICATION_MANAGE_SCOPES,
    ),
    require_all_scopes(
        model_spec(
            def(
                "associate_goal_workflow_session",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("goal_id", "/goal/summary/goal_id"),
                    super::ToolAuditResultField::pointer("revision", "/goal/summary/revision"),
                    super::ToolAuditResultField::value("replayed"),
                    super::ToolAuditResultField::value("state_changed"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                TOOL_CATEGORY_GOAL,
                None,
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: WorkflowManage,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::Keyed,
                },
                Some(COMMUNICATION_MANAGE),
                false,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            ),
            "Explicitly correlate one owned active Goal with one exact Workflow Session after independently re-authorizing the Session through its existing authority fingerprint and any bound Project authorization. The Goal link is never a Session or Project credential.",
        ),
        GOAL_SESSION_ASSOCIATE_SCOPES,
    ),
];
