use super::RunnerCapabilityRequirement::{GitOrShell, InternalPosixScript, OwnerOnly};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    adaptive_runtime_direct, def, model_spec, permission_risk, requires_explicit_business_session,
    ToolDefinition, PERMISSION_RISK_WRITE, TOOL_CATEGORY_SESSION, TOOL_CATEGORY_VALIDATION,
};
use crate::metadata::{
    ToolPathHint::None as NoPath, ToolRisk::Read, PROJECT_READ, PROJECT_WRITE, RUNTIME_READ,
    SESSION_COLLABORATE, TOOL_PROVIDER_CONTROL,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    requires_explicit_business_session(
        def(
            "record_external_observation",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelHidden,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::FencedReplay,
            },
            Some(SESSION_COLLABORATE),
            true,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE
                .lifecycle(super::ToolSessionLifecycleEffect::Mutation),
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::NonMeaningful,
        ),
    ),

    requires_explicit_business_session(model_spec(
        def(
            "list_external_observations",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible, TOOL_CATEGORY_SESSION, None, TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ), true, NoPath, false, false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::NonMeaningful,
        )
        .with_gpt_action_description("Read retained external reports for an exact Session/Project. These are untrusted adapter claims, not native execution or validation evidence; current capture completeness and source order are unproven."),
        "Read all retained external reports for an exact Session/Project (at most 256). Reports are untrusted adapter claims, separate from native Job and validation evidence. They never establish task completion or authorize replaying work. coverage remains incomplete until a durable source sequence can prove gaps/order.",
    )),

    def(
        "start_session",
        super::ToolAuditPolicy::TYPED_CANONICAL,
        ModelHidden,
        TOOL_CATEGORY_SESSION,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::WorkflowManage,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    ),
    adaptive_runtime_direct(
        model_spec(
            def(
                "work_on_project",
                super::ToolAuditPolicy::TYPED_CANONICAL,
                ModelVisible,
                "workflow",
                Some(GitOrShell),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: super::ToolRisk::WorkflowManage,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(RUNTIME_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Support,
                super::ToolActivityInteraction::Meaningful,
            ),
            "Canonical bootstrap for ordinary coding/review. Prefer project_ref; project or client_id+path work. Omit session_id for a fresh Workflow Session; it does not imply a fresh model context. Exact resume accepts session_ref or canonical session_id, requires an active accessible Session, and never guesses prior Session. Exact resume may return sparse owner-scoped goal_context for correlated active Goals; reuse one exact candidate or choose explicitly among multiple. It grants no authority and never selects/binds a Goal. For fresh or uncertain model context, request project.instructions/webcodex.workflow via context_request. Runtime re-observes instruction files; primary result stays compact. guidance_profile is model guidance only. project_ref is principal-scoped/non-authoritative; each use reauthorizes Project. include_extension_catalog controls bounded Skills/Plugins. Checkout does not require Git; mode=worktree creates an isolated worktree from an exact Git base without bypassing Project authority.",
        ).with_gpt_action_description("Start/resume exact Project work. Prefer project_ref; canonical id or client_id+path also work. Exact Session resume accepts session_ref or canonical session_id; sparse goal_context supports explicit Goal reuse without granting authority. Request project.instructions/webcodex.workflow as needed."),
        10,
    ),
    requires_explicit_business_session(model_spec(
        def(
            "finish_coding_task",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            "workflow",
            Some(GitOrShell),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            true,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity_kind(super::ToolActivityKind::Review),
        "Return an optional deterministic evidence snapshot for model review, including workspace, validation, jobs, and recorded tool events. The result is advisory: it does not decide task completion, replace direct diff or test review, or generate the user-facing final report.",
    )),
    adaptive_runtime_direct(
        model_spec(
            def(
                "present_work_result",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::pointer("project", "/work_result/project"),
                    super::ToolAuditResultField::pointer("session_id", "/work_result/session_id"),
                    super::ToolAuditResultField::pointer("state_version", "/work_result/state_version"),
                    super::ToolAuditResultField::pointer("snapshot_id", "/work_result/final_changes/snapshot_id"),
                    super::ToolAuditResultField::value("error_kind"),
                ]),
                ModelVisible,
                "workflow",
                Some(InternalPosixScript),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(PROJECT_READ),
                true,
                NoPath,
                false,
                false,
                super::ToolSessionEvidencePolicy::NONE,
            )
            .with_activity(
                super::ToolActivityPresentation::Transport,
                super::ToolActivityInteraction::NonMeaningful,
            ),
            "Present one persistent user-facing WebCodex card for the current client Window. For substantial Project work, call it once immediately after the first successful project-scoped WebCodex action so the card stays near the beginning of the chat; do not wait for Workflow Session creation, mutation, validation, or closeout. project is required; session_id is optional compatibility evidence and may be omitted. The card self-refreshes the same bounded Window ActionAudit activity used by WebUI, including observe/diagnostic actions, and may surface linked Session collaboration or sealed final changes only when those later exist. It creates no work, Session, validation, review, lifecycle change, or authority. Never repeat presentation in the same Window because another invocation may create another Host card.",
        )
        .with_gpt_action_unsupported(),
        155,
    ),
    def(
        "work_result_state",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::pointer("project", "/work_result/project"),
            super::ToolAuditResultField::pointer("session_id", "/work_result/session_id"),
            super::ToolAuditResultField::pointer("state_version", "/work_result/state_version"),
            super::ToolAuditResultField::value("error_kind"),
        ]),
        ModelHidden,
        "workflow",
        Some(GitOrShell),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_activity(
        super::ToolActivityPresentation::Transport,
        super::ToolActivityInteraction::NonMeaningful,
    ),
    def(
        "work_result_send_message",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::value("success"),
            super::ToolAuditResultField::value("session_id"),
            super::ToolAuditResultField::value("message_id"),
            super::ToolAuditResultField::value("replayed"),
            super::ToolAuditResultField::value("state_changed"),
            super::ToolAuditResultField::value("error_kind"),
        ]),
        ModelHidden,
        "workflow",
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::SessionCollaborate,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::Keyed,
        },
        Some(SESSION_COLLABORATE),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_activity(
        super::ToolActivityPresentation::Transport,
        super::ToolActivityInteraction::NonMeaningful,
    ),
    def(
        "changes_file_diff",
        super::ToolAuditPolicy::typed_fields(&[
            super::ToolAuditResultField::pointer("project", "/changes_file_diff/project"),
            super::ToolAuditResultField::pointer("session_id", "/changes_file_diff/session_id"),
            super::ToolAuditResultField::pointer("snapshot_id", "/changes_file_diff/snapshot_id"),
            super::ToolAuditResultField::pointer("path", "/changes_file_diff/path"),
            super::ToolAuditResultField::value("error_kind"),
        ]),
        ModelHidden,
        "workflow",
        Some(InternalPosixScript),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
        super::ToolSessionEvidencePolicy::NONE,
    )
    .with_activity(
        super::ToolActivityPresentation::Transport,
        super::ToolActivityInteraction::NonMeaningful,
    ),
    requires_explicit_business_session(model_spec(
        def(
            "session_summary",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Return a bounded structured summary from the session ledger for an explicit session_id: recorded events, message-board summary, task mode, guards, and lifecycle. Uses durable ledger data where session persistence is configured.",
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "update_session_context",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Update Session defaults. Binding execution_context.resource selects an already active Runner-local named SSH resource; for a new explicit target use ssh_resource list/register and restart the Runner first, then list and bind the active name. open_session_shell uses that Session binding. Requires an authorized project matching the exact Session project; cross-project escape is not supported. Context and event commit under the store lock; the background writer persists, so success does not mean disk flush. Never falls back and never creates unknown Sessions.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "close_session",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.persistent_shell(super::PersistentShellEvidenceAction::Close).lifecycle(super::ToolSessionLifecycleEffect::IdempotentClose),
            ),
            "Explicitly close a workflow session (Active to Closed) for a required session_id. Query remains available; write/shell/mutation tools are denied. Idempotent when already closed; unknown ids fail without create. finish_coding_task does not close.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "validation_summary",
            super::ToolAuditPolicy::TYPED_CANONICAL,
            ModelVisible,
            TOOL_CATEGORY_VALIDATION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::Meaningful,
        ),
        "Read bounded structured validation evidence already recorded in an explicit project-scoped session ledger. Does not run Cargo or shell commands, enqueue a Runner request, read project files, mutate the workspace, or replace finish_coding_task.",
    )),
    requires_explicit_business_session(model_spec(
        def(
            "post_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::pointer("kind", "/message/kind"),
                super::ToolAuditResultField::pointer("status", "/message/status"),
                super::ToolAuditResultField::pointer("requires_ack", "/message/requires_ack"),
                super::ToolAuditResultField::pointer("author_session_id", "/message/author_session_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
        ),
        "Post a bounded collaboration message (todo, question, progress, guidance, risk, or decision). Optional delivery_key provides bounded restart-safe sender-scoped replay while the keyed message metadata remains retained; exact retries return the original message and conflicting retained key reuse fails closed. Any message may request request-scoped ACK; ACK proves only current model-context retention and neither resolves nor gates work. Use complete_session_message to atomically answer and resolve a finished todo.",
    )),
    model_spec(
        def(
            "post_peer_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::value("sender_peer_id"),
                super::ToolAuditResultField::value("recipient_peer_id"),
                super::ToolAuditResultField::value("requires_ack"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Send a bounded message to a principal-scoped peer window discovered through peer_awareness. Optional delivery_key provides bounded restart-safe principal-and-sender-Window replay while the keyed peer message remains retained; exact retries return the original message and conflicting retained key reuse fails closed. Routing does not require Project equality, so a Project/worktree change alone does not invalidate the retained route; it grants no access to the recipient's Project, Workflow Session, files, or assignment authority. Ordinary messages are projected once; requires_ack messages repeat while retained whenever the recipient omits the request-scoped ACK.",
    ),
    requires_explicit_business_session(model_spec(
        def(
            "list_session_messages",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::array_len("message_count", "messages"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Read bounded session-local messages with exact filters. For an executable todo, prefer get_session_assignment so the todo, all retained direct replies, and its completion fence come from one store snapshot.",
    )),
    requires_explicit_business_session(model_spec(
        def(
            "get_session_assignment",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::array_len("direct_reply_count", "direct_replies"),
                super::ToolAuditResultField::string_present("assignment_fence_present", "assignment_fence"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Atomically read one exact open todo plus all retained direct replies and return the opaque assignment_fence required by complete_session_message. Unrelated Session traffic and ACK bookkeeping do not stale it; incomplete retained assignment history fails closed.",
    )),
    requires_explicit_business_session(model_spec(
        def(
            "observe_session_messages",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::array_len("message_count", "messages"),
                super::ToolAuditResultField::value("changed"),
                super::ToolAuditResultField::value("history_lost"),
                super::ToolAuditResultField::value("has_more"),
                super::ToolAuditResultField::value("wait_outcome"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Observe Session message-state delta after an opaque durable cursor. No token establishes the current baseline and returns no history; token calls may wait once for change. Reports retention loss; never a subscription, delivery receipt, or model-context proof.",
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "resolve_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::pointer("status", "/message/status"),
                super::ToolAuditResultField::pointer("resolved_by_message_id", "/message/resolved_by_message_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Mark a session-local ledger message resolved. Idempotent when the message is already resolved; metadata-only and never modifies project files.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    requires_explicit_business_session(permission_risk(
        model_spec(
            def(
            "complete_session_message",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("success"),
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("message_id"),
                super::ToolAuditResultField::value("answer_message_id"),
                super::ToolAuditResultField::value("completion_id"),
                super::ToolAuditResultField::value("replayed"),
                super::ToolAuditResultField::pointer("author_session_id", "/answer/author_session_id"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::FencedReplay,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            true,
            false,
            super::ToolSessionEvidencePolicy::NONE.lifecycle(super::ToolSessionLifecycleEffect::Mutation),
            ),
            "Atomically answer and resolve one exact open todo. expected_assignment_fence is required and must be the exact opaque fence from get_session_assignment; completion_key separately keeps uncertain-result retries idempotent.",
        ),
        PERMISSION_RISK_WRITE,
    )),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "session_discussion_summary",
                super::ToolAuditPolicy::typed_fields(&[
                    super::ToolAuditResultField::value("success"),
                    super::ToolAuditResultField::value("session_id"),
                    super::ToolAuditResultField::value("counts"),
                    super::ToolAuditResultField::array_len("open_todo_count", "open_todos"),
                    super::ToolAuditResultField::array_len("recent_answer_count", "recent_answers"),
                    super::ToolAuditResultField::array_len("recent_completion_count", "recent_completions"),
                ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        ),
        "Return a bounded structured aggregate of session-local discussion from the recorded session ledger. Does not call an LLM or generate natural-language summaries.",
        )),
        15,
    ),
    adaptive_runtime_direct(
        requires_explicit_business_session(model_spec(
            def(
                "session_handoff_summary",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("project"),
                super::ToolAuditResultField::value("lifecycle"),
                super::ToolAuditResultField::value("counts"),
                super::ToolAuditResultField::array_len("open_todo_count", "open_todos"),
                super::ToolAuditResultField::array_len("recent_answer_count", "recent_answers"),
                super::ToolAuditResultField::array_len("recent_completion_count", "recent_completions"),
                super::ToolAuditResultField::value("diagnostic"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::Meaningful,
        ),
            "Explicit read-only recovery for genuinely missing task context or an explicit handoff; requires the exact session_id or its returned session_ref selector. Do not use as routine progress/status polling or to establish a Session baseline when current context is coherent. Defaults to identity plus deterministic handoff_brief, hard-bounded at 8 KiB: task instructions, workspace, progress, validation, jobs, collaboration attention, bounded external reports, next actions and basis completeness. External reports retain exact source IDs and unknown outcomes, with incomplete capture coverage; they are not native execution or validation. Omitted project uses the authorized Session Project. diagnostic=true adds detailed ledger and closeout evidence. A concurrent Session change marks the basis incomplete; re-observe before dependent work. No checkpoint allocation, ACK token, or authority grant.",
        ).with_gpt_action_description("Recover missing task context or perform an explicit handoff for the exact session_id or returned session_ref. Avoid routine status polling or baseline creation. Returns bounded handoff_brief; diagnostic=true adds evidence. Check basis completeness before dependent work. Read-only.")),
        16,
    ),
    requires_explicit_business_session(
        def(
            "session_handoff_state",
            super::ToolAuditPolicy::typed_fields(&[
                super::ToolAuditResultField::value("session_id"),
                super::ToolAuditResultField::value("project"),
                super::ToolAuditResultField::value("error_kind"),
            ]),
            ModelHidden,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            true,
            NoPath,
            false,
            false,
            super::ToolSessionEvidencePolicy::NONE,
        )
        .with_activity(
            super::ToolActivityPresentation::Support,
            super::ToolActivityInteraction::NonMeaningful,
        ),
    ),
];
