use super::AgentCapability::{FileRead, FileWrite};
use super::ToolVisibility::ModelVisible;
use super::{def, requires_artifact_upload_path_binding, ToolDefinition, TOOL_CATEGORY_ARTIFACT};
use crate::tool_runtime::metadata::{
    ToolPathHint::Artifact,
    ToolRisk::{ProjectWrite, Read},
    PROJECT_READ, PROJECT_WRITE, TOOL_PROVIDER_AGENT, TOOL_PROVIDER_CONTROL,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    def(
        "save_project_artifact",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Artifact,
        false,
        false,
    ),
    def(
        "import_conversation_files_to_project",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileWrite),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Artifact,
        false,
        false,
    ),
    def(
        "export_project_artifact",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileRead),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        Artifact,
        false,
        false,
    ),
    def(
        "read_project_artifact_metadata",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileRead),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        Artifact,
        false,
        false,
    ),
    def(
        "read_project_artifact",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileRead),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        Artifact,
        false,
        false,
    ),
    def(
        "artifact_upload_begin",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Artifact,
        false,
        false,
    ),
    requires_artifact_upload_path_binding(def(
        "artifact_upload_chunk",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Artifact,
        false,
        false,
    )),
    requires_artifact_upload_path_binding(def(
        "artifact_upload_finish",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Artifact,
        false,
        false,
    )),
    requires_artifact_upload_path_binding(def(
        "artifact_upload_abort",
        ModelVisible,
        TOOL_CATEGORY_ARTIFACT,
        Some(FileWrite),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Artifact,
        false,
        false,
    )),
];
