use super::AgentCapability::{FileRead, FileWrite, OwnerOnly};
use super::ToolVisibility::ModelVisible;
use super::{def, git_like, ToolDefinition, TOOL_CATEGORY_CHECKPOINT};
use crate::tool_runtime::metadata::{
    ToolPathHint::{None as NoPath, Patch},
    ToolRisk::{ProjectWrite, ReadOnly},
    PROJECT_READ, PROJECT_WRITE,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    git_like(def(
        "workspace_checkpoint_create",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(FileRead),
        "native",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    )),
    def(
        "workspace_checkpoint_list",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(OwnerOnly),
        "native",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "workspace_checkpoint_show",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(OwnerOnly),
        "native",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    git_like(def(
        "workspace_checkpoint_restore",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(FileWrite),
        "native",
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        Patch,
        false,
        false,
    )),
    def(
        "workspace_checkpoint_delete",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(OwnerOnly),
        "native",
        ProjectWrite,
        Some(PROJECT_WRITE),
        true,
        NoPath,
        true,
        false,
    ),
];
