use super::AgentCapability::{FileRead, FileWrite, OwnerOnly};
use super::ToolVisibility::ModelVisible;
use super::{def, git_like, ToolDefinition, TOOL_CATEGORY_CHECKPOINT};
use crate::tool_runtime::metadata::{
    ToolPathHint::{None as NoPath, Patch},
    ToolRisk::{ProjectWrite, Read},
    PROJECT_READ, PROJECT_WRITE, TOOL_PROVIDER_NATIVE,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    git_like(def(
        "workspace_checkpoint_create",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(FileRead),
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::CheckpointManage,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    )),
    def(
        "workspace_checkpoint_list",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(OwnerOnly),
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "workspace_checkpoint_show",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(OwnerOnly),
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    git_like(def(
        "workspace_checkpoint_restore",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(FileWrite),
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        Patch,
        false,
        false,
    )),
    def(
        "workspace_checkpoint_delete",
        ModelVisible,
        TOOL_CATEGORY_CHECKPOINT,
        Some(OwnerOnly),
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: ProjectWrite,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(PROJECT_WRITE),
        true,
        NoPath,
        true,
        false,
    ),
];
