use super::AgentCapability::{
    ComputerAccessibilityObserve, ComputerApplicationDiscovery, ComputerApplicationLaunch,
    ComputerClipboardRead, ComputerClipboardWrite, ComputerControl, ComputerDisplayObserve,
    ComputerElementState, ComputerKeyInput, ComputerObserve, ComputerPointerControl,
    ComputerScrollToElement, ComputerTextInput, ComputerWindowActivate, FileWrite,
};
use super::ToolVisibility::ModelVisible;
use super::{def, require_all_scopes, unit_arguments, ToolDefinition, TOOL_CATEGORY_COMPUTER};
use crate::tool_runtime::metadata::{
    ToolPathHint::{Artifact, None},
    ToolRisk::{ComputerControl as ComputerControlRisk, ProjectWrite, Read},
    COMPUTER_CLIPBOARD_READ, COMPUTER_CLIPBOARD_WRITE, COMPUTER_CONTROL, COMPUTER_DISPLAY_READ,
    COMPUTER_LAUNCH, COMPUTER_POINTER_CONTROL, COMPUTER_READ, PROJECT_WRITE, TOOL_PROVIDER_AGENT,
    TOOL_PROVIDER_CONTROL,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        def(
            "computer_read_clipboard",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerClipboardRead),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_CLIPBOARD_READ),
            false,
            None,
            false,
            false,
        ),
        &[COMPUTER_READ, COMPUTER_CLIPBOARD_READ],
    ),
    require_all_scopes(
        def(
            "computer_write_clipboard",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerClipboardWrite),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_CLIPBOARD_WRITE),
            false,
            None,
            false,
            false,
        ),
        &[COMPUTER_CONTROL, COMPUTER_CLIPBOARD_WRITE],
    ),
    require_all_scopes(
        def(
            "computer_pointer_move",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerPointerControl),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_POINTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        &[
            COMPUTER_READ,
            COMPUTER_DISPLAY_READ,
            COMPUTER_CONTROL,
            COMPUTER_POINTER_CONTROL,
        ],
    ),
    require_all_scopes(
        def(
            "computer_pointer_click",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerPointerControl),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_POINTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        &[
            COMPUTER_READ,
            COMPUTER_DISPLAY_READ,
            COMPUTER_CONTROL,
            COMPUTER_POINTER_CONTROL,
        ],
    ),
    unit_arguments(def(
        "computer_list_targets",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        std::option::Option::None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    )),
    def(
        "computer_list_windows",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerObserve),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    require_all_scopes(
        def(
            "computer_list_displays",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerDisplayObserve),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_DISPLAY_READ),
            false,
            None,
            false,
            false,
        ),
        &[COMPUTER_READ, COMPUTER_DISPLAY_READ],
    ),
    def(
        "computer_list_applications",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerApplicationDiscovery),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_launch_application",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerApplicationLaunch),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: ComputerControlRisk,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(COMPUTER_LAUNCH),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_accessibility_status",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerAccessibilityObserve),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_accessibility_tree",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerAccessibilityObserve),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_find_elements",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerAccessibilityObserve),
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_element_state",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerElementState),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_activate_window",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerWindowActivate),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: ComputerControlRisk,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(COMPUTER_CONTROL),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_control",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerControl),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: ComputerControlRisk,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(COMPUTER_CONTROL),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_scroll_to_element",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerScrollToElement),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: ComputerControlRisk,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(COMPUTER_CONTROL),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_key_input",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerKeyInput),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: ComputerControlRisk,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(COMPUTER_CONTROL),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_input_text",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerTextInput),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: ComputerControlRisk,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(COMPUTER_CONTROL),
        false,
        None,
        false,
        false,
    ),
    def(
        "computer_snapshot",
        ModelVisible,
        TOOL_CATEGORY_COMPUTER,
        Some(ComputerObserve),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(COMPUTER_READ),
        false,
        None,
        false,
        false,
    ),
    require_all_scopes(
        def(
            "computer_snapshot_display",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerDisplayObserve),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_DISPLAY_READ),
            false,
            None,
            false,
            false,
        ),
        &[COMPUTER_READ, COMPUTER_DISPLAY_READ],
    ),
    require_all_scopes(
        def(
            "computer_save_snapshot",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(FileWrite),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: ProjectWrite,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            Artifact,
            false,
            false,
        ),
        &[PROJECT_WRITE, COMPUTER_READ],
    ),
];
