use super::AgentCapability::{
    ComputerAccessibilityObserve, ComputerApplicationDiscovery, ComputerApplicationLaunch,
    ComputerClipboardRead, ComputerClipboardWrite, ComputerControl, ComputerDisplayObserve,
    ComputerElementState, ComputerKeyInput, ComputerObserve, ComputerPointerControl,
    ComputerScrollToElement, ComputerTextInput, ComputerWindowActivate, FileWrite,
};
use super::ToolVisibility::ModelVisible;
use super::{
    def, model_spec, require_all_scopes, unit_arguments, ToolDefinition, TOOL_CATEGORY_COMPUTER,
};
use crate::tool_runtime::metadata::{
    ToolPathHint::{Artifact, None},
    ToolRisk::{ComputerControl as ComputerControlRisk, ProjectWrite, Read},
    COMPUTER_CLIPBOARD_READ, COMPUTER_CLIPBOARD_WRITE, COMPUTER_CONTROL, COMPUTER_DISPLAY_READ,
    COMPUTER_LAUNCH, COMPUTER_POINTER_CONTROL, COMPUTER_READ, PROJECT_WRITE, TOOL_PROVIDER_AGENT,
    TOOL_PROVIDER_CONTROL,
};
use crate::tool_runtime::registry::input_schemas::{
    computer_accessibility_status_input_schema, computer_accessibility_tree_input_schema,
    computer_activate_window_input_schema, computer_control_input_schema,
    computer_element_state_input_schema, computer_find_elements_input_schema,
    computer_input_text_input_schema, computer_key_input_input_schema,
    computer_launch_application_input_schema, computer_list_applications_input_schema,
    computer_list_displays_input_schema, computer_list_windows_input_schema,
    computer_pointer_input_schema, computer_read_clipboard_input_schema,
    computer_save_snapshot_input_schema, computer_scroll_to_element_input_schema,
    computer_snapshot_display_input_schema, computer_snapshot_input_schema,
    computer_write_clipboard_input_schema, empty_input_schema,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    require_all_scopes(
        model_spec(
            def(
                "computer_read_clipboard",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(ComputerClipboardRead),
                TOOL_PROVIDER_AGENT,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMPUTER_CLIPBOARD_READ),
                false,
                None,
                false,
                false,
            ),
            "Read bounded Unicode text from exact macOS or Windows clipboard using NSPasteboardTypeString or CF_UNICODETEXT. Returns UTF-8 up to 16 KiB without truncation. This privacy authority never enumerates formats, accesses windows/focus, pastes, retries, uses shell fallback, or reads history.",
            computer_read_clipboard_input_schema,
        ),
        &[COMPUTER_READ, COMPUTER_CLIPBOARD_READ],
    ),
    require_all_scopes(
        model_spec(
            def(
                "computer_write_clipboard",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(ComputerClipboardWrite),
                TOOL_PROVIDER_AGENT,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Execute,
                    risk: ComputerControlRisk,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(COMPUTER_CLIPBOARD_WRITE),
                false,
                None,
                false,
                false,
            ),
            "Replace exact macOS or Windows clipboard with bounded Unicode text using NSPasteboardTypeString or CF_UNICODETEXT, clearing prior formats. Never pastes, focuses, activates, restores, retries, or reads back implicitly. Unknown outcomes require separate clipboard-read reconciliation.",
            computer_write_clipboard_input_schema,
        ),
        &[COMPUTER_CONTROL, COMPUTER_CLIPBOARD_WRITE],
    ),
    require_all_scopes(
        model_spec(
            def(
                "computer_pointer_move",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(ComputerPointerControl),
                TOOL_PROVIDER_AGENT,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Execute,
                    risk: ComputerControlRisk,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(COMPUTER_POINTER_CONTROL),
                false,
                None,
                false,
                false,
            ),
            "Move the macOS or Windows pointer to an exact display-local source coordinate using the latest unspent snapshot generation. The generation is single-use at effect admission. No implicit observation, focus, drag, fallback, or retry; reconcile unknown outcomes with fresh computer_snapshot_display.",
            computer_pointer_input_schema,
        ),
        &[
            COMPUTER_READ,
            COMPUTER_DISPLAY_READ,
            COMPUTER_CONTROL,
            COMPUTER_POINTER_CONTROL,
        ],
    ),
    require_all_scopes(
        model_spec(
            def(
                "computer_pointer_click",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(ComputerPointerControl),
                TOOL_PROVIDER_AGENT,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Execute,
                    risk: ComputerControlRisk,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(COMPUTER_POINTER_CONTROL),
                false,
                None,
                false,
                false,
            ),
            "Send a macOS or Windows left click at exact display-local source coordinates using the unspent snapshot generation. Held mouse/modifier state fails closed. No other buttons, double click, drag, implicit snapshot, fallback, or retry; reconcile unknown outcomes with fresh computer_snapshot_display.",
            computer_pointer_input_schema,
        ),
        &[
            COMPUTER_READ,
            COMPUTER_DISPLAY_READ,
            COMPUTER_CONTROL,
            COMPUTER_POINTER_CONTROL,
        ],
    ),
    unit_arguments(model_spec(
        def(
            "computer_list_targets",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            std::option::Option::None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "List caller-visible Runners that advertise Computer observation or application capabilities. Use when client_id is unknown. Returns only target identity, connection state, and independent Computer capability facts; no projects, policy, jobs, host details, or observation content.",
        empty_input_schema,
    )),
    model_spec(
        def(
            "computer_list_windows",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerObserve),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "List a bounded set of observable top-level windows on an exact Runner. surface_id values are opaque, process-local, and ephemeral. focused is exact-window focus when reliably known; active is the platform active/frontmost signal and may be application-level on macOS.",
        computer_list_windows_input_schema,
    ),
    require_all_scopes(
        model_spec(
            def(
                "computer_list_displays",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(ComputerDisplayObserve),
                TOOL_PROVIDER_AGENT,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMPUTER_DISPLAY_READ),
                false,
                None,
                false,
                false,
            ),
            "List bounded fresh full displays on an exact macOS or Windows Runner. IDs are opaque, process-local, ephemeral, and replaced on each list. Returns only display-relative dimensions and primary status; native identity, global origin, scale, and topology stay private.",
            computer_list_displays_input_schema,
        ),
        &[COMPUTER_READ, COMPUTER_DISPLAY_READ],
    ),
    model_spec(
        def(
            "computer_list_applications",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerApplicationDiscovery),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "List a bounded fresh set of installed applications on an exact macOS or Windows Runner. application_id values are opaque, process-local, ephemeral, and replaced by each fresh list; application paths, bundle/Shell identities, and native launch targets are never exposed.",
        computer_list_applications_input_schema,
    ),
    model_spec(
        def(
            "computer_launch_application",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerApplicationLaunch),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_LAUNCH),
            false,
            None,
            false,
            false,
        ),
        "Launch one fresh application_id through its exact macOS or Windows application target. Accepts no path, argv, cwd, environment, shell, URL, fallback, focus, or activation. Success proves only bounded launch completion, not process/window readiness; reconcile unknown outcomes with fresh windows.",
        computer_launch_application_input_schema,
    ),
    model_spec(
        def(
            "computer_accessibility_status",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerAccessibilityObserve),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "Read the exact Runner's native accessibility availability/trust status without prompting or changing system permission state. Supports macOS Accessibility and Windows UI Automation.",
        computer_accessibility_status_input_schema,
    ),
    model_spec(
        def(
            "computer_accessibility_tree",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerAccessibilityObserve),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "Inspect an exact macOS or Windows window as a bounded read-only native accessibility tree. element_id values are ephemeral process-local handles; this tool performs no control action and has no shell or platform-script fallback.",
        computer_accessibility_tree_input_schema,
    ),
    model_spec(
        def(
            "computer_find_elements",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerAccessibilityObserve),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "Find bounded semantic elements on an exact macOS or Windows window without parsing the full native accessibility tree. Requires at least one role, subrole, label, focused, or enabled filter. Matching is deterministic and read-only; returned element_id values are fresh ephemeral handles.",
        computer_find_elements_input_schema,
    ),
    model_spec(
        def(
            "computer_element_state",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerElementState),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "Revalidate an exact ephemeral accessibility element and return normalized read-only affordances plus observation generation. Supports macOS AX and Windows UIA; never returns element values. Protected or secure targets suppress value_empty. Reacquire stale handles with computer_find_elements.",
        computer_element_state_input_schema,
    ),
    model_spec(
        def(
            "computer_activate_window",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerWindowActivate),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        "Activate and raise one exact previously observed macOS or Windows window surface. The tool accepts no app name, PID, path, bundle, command, or fallback target. Stale surfaces fail closed; if delivery may have occurred but the response is lost, observe current UI state before retrying.",
        computer_activate_window_input_schema,
    ),
    model_spec(
        def(
            "computer_control",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerControl),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        "Perform native macOS Accessibility or Windows UI Automation press/focus on an exact reusable element_id. Stale, protected, disabled, or unsupported targets fail closed. There is no script, shell, coordinate, or generic fallback; uncertain post-dispatch outcomes require re-observation.",
        computer_control_input_schema,
    ),
    model_spec(
        def(
            "computer_scroll_to_element",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerScrollToElement),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        "Scroll one exact macOS Accessibility or Windows UIA element into view with the native semantic scroll action. Stale, mismatched, unsupported, or protected targets fail closed; no wheel, coordinate, script, or shell fallback. Unknown post-dispatch outcomes require re-observation before retrying.",
        computer_scroll_to_element_input_schema,
    ),
    model_spec(
        def(
            "computer_key_input",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerKeyInput),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        "Send one closed key to an exact revalidated frontmost/focused macOS or Windows window. Windows rejects command, unsafe system chords, and interfering held keys; input uses the shared input stream. No text, keycodes, repeat/held state, implicit focus, or fallback. Re-observe unknown outcomes.",
        computer_key_input_input_schema,
    ),
    model_spec(
        def(
            "computer_input_text",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerTextInput),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: ComputerControlRisk,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(COMPUTER_CONTROL),
            false,
            None,
            false,
            false,
        ),
        "Write bounded text via macOS AXValue or Windows UIA ValuePattern to an exact element_id. Target must be focused, non-secure, unprotected, supported, enabled, writable, and empty; Windows must be foreground. No focus/activation, paste, key, or send fallback. Re-observe unknown outcomes.",
        computer_input_text_input_schema,
    ),
    model_spec(
        def(
            "computer_snapshot",
            ModelVisible,
            TOOL_CATEGORY_COMPUTER,
            Some(ComputerObserve),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(COMPUTER_READ),
            false,
            None,
            false,
            false,
        ),
        "Capture one exact listed window as a bounded image. Optional surface-relative region or max dimensions require the region-snapshot capability; whole-window capture stays rolling-compatible. Region must fit the revalidated surface. Encoding is system-selected; stale surfaces never fall back.",
        computer_snapshot_input_schema,
    ),
    require_all_scopes(
        model_spec(
            def(
                "computer_snapshot_display",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(ComputerDisplayObserve),
                TOOL_PROVIDER_AGENT,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Observe,
                    risk: Read,
                    approval: super::ToolApprovalPolicy::None,
                    idempotency: super::ToolIdempotency::PureRead,
                },
                Some(COMPUTER_DISPLAY_READ),
                false,
                None,
                false,
                false,
            ),
            "Capture one discovered full display on an exact macOS or Windows Runner after private native-identity revalidation. Stale or ambiguous displays fail closed; max dimensions only downscale. No global coordinates, regions, activation, input, shell, or fallback. Returns a positive snapshot generation.",
            computer_snapshot_display_input_schema,
        ),
        &[COMPUTER_READ, COMPUTER_DISPLAY_READ],
    ),
    require_all_scopes(
        model_spec(
            def(
                "computer_save_snapshot",
                ModelVisible,
                TOOL_CATEGORY_COMPUTER,
                Some(FileWrite),
                TOOL_PROVIDER_CONTROL,
                super::ToolSemanticContract {
                    effect: super::ToolEffect::Mutate,
                    risk: ProjectWrite,
                    approval: super::ToolApprovalPolicy::Standard,
                    idempotency: super::ToolIdempotency::NonIdempotent,
                },
                Some(PROJECT_WRITE),
                true,
                Artifact,
                false,
                false,
            ),
            "Save one exact window snapshot as a create-only project artifact without returning image bytes. Reuses computer_snapshot region/downscale semantics and requires computer:read plus project:write. No overwrite or encoding control. Unknown writes require artifact-metadata reconciliation before retry.",
            computer_save_snapshot_input_schema,
        ),
        &[PROJECT_WRITE, COMPUTER_READ],
    ),
];
