use super::ToolVisibility::ModelVisible;
use super::{
    def, model_spec, unit_arguments, ToolDefinition, TOOL_CATEGORY_PROJECT, TOOL_CATEGORY_RUNTIME,
};
use crate::tool_runtime::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{ProjectWrite, ReadOnly},
    PROJECT_READ, PROJECT_WRITE, RUNTIME_READ, TOOL_PROVIDER_CONTROL,
};
use crate::tool_runtime::registry::input_schemas::{
    create_project_input_schema, empty_input_schema, register_project_input_schema,
    runtime_status_input_schema, tool_manifest_input_schema, unregister_project_input_schema,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    model_spec(
        unit_arguments(def(
            "list_projects",
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            ReadOnly,
            Some(PROJECT_READ),
            false,
            NoPath,
            false,
            false,
        )),
        "List agent-registered runtime projects, execution mode, and smoke-selection capabilities such as git_available and recommended_for_smoke.",
        empty_input_schema,
    ),
    model_spec(
        def(
            "register_project",
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            ProjectWrite,
            Some(PROJECT_WRITE),
            false,
            NoPath,
            true,
            false,
        ),
        "Register an existing directory, including a non-Git or ad-hoc workspace, as a Project on one Runner. Use this when the directory already exists; policy still bounds allowed paths.",
        register_project_input_schema,
    ),
    model_spec(
        def(
            "unregister_project",
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            ProjectWrite,
            Some(PROJECT_WRITE),
            false,
            NoPath,
            true,
            false,
        ),
        "Unregister one exact Runner project using the revision from list_projects. Removes registration only; never deletes source, worktree, or branch. Re-list after an indeterminate outcome.",
        unregister_project_input_schema,
    ),
    model_spec(
        def(
            "create_project",
            ModelVisible,
            TOOL_CATEGORY_PROJECT,
            None,
            TOOL_PROVIDER_CONTROL,
            ProjectWrite,
            Some(PROJECT_WRITE),
            false,
            NoPath,
            true,
            false,
        ),
        "Create a directory on one Runner and register it as a Project. Use this for a new workspace; existing directories belong on the registration path.",
        create_project_input_schema,
    ),
    model_spec(
        unit_arguments(def(
            "list_agents",
            ModelVisible,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            ReadOnly,
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        )),
        "List authorized Runners with identity, connectivity, capabilities, Projects, and shared Job concurrency. host_context is bounded Runner-configured advisory data, never authority or proof of current state.",
        empty_input_schema,
    ),
    model_spec(
        def(
            "runtime_status",
            ModelVisible,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            ReadOnly,
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Read Server/Project/Runner observations, build/source diagnostics, and shared Job concurrency. host_context is bounded configured advisory data, not observed truth or authority. compact=true returns a small snapshot.",
        runtime_status_input_schema,
    ),
    model_spec(
        def(
            "tool_manifest",
            ModelVisible,
            TOOL_CATEGORY_RUNTIME,
            None,
            TOOL_PROVIDER_CONTROL,
            ReadOnly,
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Return a compact, bounded tool manifest with categories, flattened args, risk, flows, and optional coding/audit/exploration/release/discovery intent views. Intents only filter and rank discovery; they do not change behavior, policy, permissions, execution, or verdicts. Read-only.",
        tool_manifest_input_schema,
    ),
];
