use super::ToolVisibility::ModelVisible;
use super::{def, unit_arguments, ToolDefinition, TOOL_CATEGORY_PROJECT, TOOL_CATEGORY_RUNTIME};
use crate::tool_runtime::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{ProjectWrite, ReadOnly},
    PROJECT_READ, PROJECT_WRITE, RUNTIME_READ, TOOL_PROVIDER_CONTROL,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    unit_arguments(def(
        "list_projects",
        ModelVisible,
        TOOL_CATEGORY_PROJECT,
        None,
        TOOL_PROVIDER_CONTROL,
        ReadOnly,
        Some(PROJECT_READ),
        false,
        NoPath,
        false,
        false,
    )),
    def(
        "register_project",
        ModelVisible,
        TOOL_CATEGORY_PROJECT,
        None,
        TOOL_PROVIDER_CONTROL,
        ProjectWrite,
        Some(PROJECT_WRITE),
        false,
        NoPath,
        true,
        false,
    ),
    def(
        "create_project",
        ModelVisible,
        TOOL_CATEGORY_PROJECT,
        None,
        TOOL_PROVIDER_CONTROL,
        ProjectWrite,
        Some(PROJECT_WRITE),
        false,
        NoPath,
        true,
        false,
    ),
    unit_arguments(def(
        "list_agents",
        ModelVisible,
        TOOL_CATEGORY_RUNTIME,
        None,
        TOOL_PROVIDER_CONTROL,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    )),
    unit_arguments(def(
        "runtime_status",
        ModelVisible,
        TOOL_CATEGORY_RUNTIME,
        None,
        TOOL_PROVIDER_CONTROL,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    )),
    def(
        "tool_manifest",
        ModelVisible,
        TOOL_CATEGORY_RUNTIME,
        None,
        TOOL_PROVIDER_CONTROL,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
];
