use super::AgentCapability::{FileRead, Shell};
use super::ToolVisibility::ModelVisible;
use super::{def, ToolDefinition, TOOL_CATEGORY_FILE, TOOL_CATEGORY_PROJECT};
use crate::tool_runtime::metadata::{
    ToolPathHint::{None as NoPath, SinglePath},
    ToolRisk::Read,
    PROJECT_READ, TOOL_PROVIDER_AGENT,
};

pub(super) const SEARCH_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "project_overview",
        ModelVisible,
        TOOL_CATEGORY_PROJECT,
        Some(FileRead),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "list_project_files",
        ModelVisible,
        TOOL_CATEGORY_FILE,
        Some(FileRead),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "list_project_tracked_files",
        ModelVisible,
        TOOL_CATEGORY_FILE,
        // Runs `git ls-files` on the agent, so the shell capability is what
        // the agent must actually hold — not FileRead's directory op.
        Some(Shell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "search_project_text",
        ModelVisible,
        TOOL_CATEGORY_FILE,
        Some(Shell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
    def(
        "search_project_texts",
        ModelVisible,
        TOOL_CATEGORY_FILE,
        Some(Shell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
];

pub(super) const READ_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "read_file",
        ModelVisible,
        TOOL_CATEGORY_FILE,
        Some(FileRead),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        SinglePath,
        false,
        false,
    ),
    def(
        "read_files",
        ModelVisible,
        TOOL_CATEGORY_FILE,
        Some(FileRead),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ),
];
