use super::AgentCapability::GitOrShell;
use super::ToolVisibility::ModelVisible;
use super::{change_summary_like, def, git_like, ToolDefinition};
use crate::tool_runtime::metadata::{
    ToolPathHint::None as NoPath, ToolRisk::ReadOnly, PROJECT_READ,
};

pub(super) const SUMMARY_DEFINITIONS: &[ToolDefinition] = &[
    change_summary_like(git_like(def(
        "git_diff_summary",
        ModelVisible,
        "git",
        Some(GitOrShell),
        "agent",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ))),
    change_summary_like(git_like(def(
        "show_changes",
        ModelVisible,
        "git",
        Some(GitOrShell),
        "agent",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ))),
];

pub(super) const DETAIL_DEFINITIONS: &[ToolDefinition] = &[
    git_like(def(
        "git_status",
        ModelVisible,
        "git",
        Some(GitOrShell),
        "agent",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    )),
    git_like(def(
        "git_diff",
        ModelVisible,
        "git",
        Some(GitOrShell),
        "agent",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    )),
    change_summary_like(git_like(def(
        "git_diff_hunks",
        ModelVisible,
        "git",
        Some(GitOrShell),
        "agent",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    ))),
    git_like(def(
        "git_log",
        ModelVisible,
        "git",
        Some(GitOrShell),
        "agent",
        ReadOnly,
        Some(PROJECT_READ),
        true,
        NoPath,
        false,
        false,
    )),
];
