use super::AgentCapability::{
    AsyncJobs, DetachedProcess, PersistentShell, Shell, StructuredProcess, StructuredScript,
};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    def, permission_risk, require_all_scopes, requires_explicit_business_session, ToolDefinition,
    PERMISSION_RISK_JOB, TOOL_CATEGORY_JOB,
};
use crate::auth::scopes::SCOPE_JOB_DETACH;
use crate::tool_runtime::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{JobRun, Read},
    JOB_RUN, RUNTIME_READ, TOOL_PROVIDER_AGENT, TOOL_PROVIDER_NATIVE,
};

pub(super) const EXECUTION_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "run_process",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(StructuredProcess),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: JobRun,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(JOB_RUN),
        true,
        NoPath,
        true,
        true,
    ),
    require_all_scopes(
        def(
            "run_detached_process",
            ModelVisible,
            TOOL_CATEGORY_JOB,
            Some(DetachedProcess),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: JobRun,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::Keyed,
            },
            Some(JOB_RUN),
            true,
            NoPath,
            true,
            true,
        ),
        &[JOB_RUN, SCOPE_JOB_DETACH],
    ),
    def(
        "run_script",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(StructuredScript),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: JobRun,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(JOB_RUN),
        true,
        NoPath,
        true,
        true,
    ),
    def(
        "run_shell",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(Shell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: JobRun,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(JOB_RUN),
        true,
        NoPath,
        true,
        true,
    ),
    requires_explicit_business_session(def(
        "open_session_shell",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(PersistentShell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: JobRun,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(JOB_RUN),
        true,
        NoPath,
        true,
        true,
    )),
    requires_explicit_business_session(def(
        "session_shell_exec",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(PersistentShell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Execute,
            risk: JobRun,
            approval: super::ToolApprovalPolicy::Standard,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(JOB_RUN),
        true,
        NoPath,
        true,
        true,
    )),
    requires_explicit_business_session(def(
        "session_shell_status",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(PersistentShell),
        TOOL_PROVIDER_AGENT,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(RUNTIME_READ),
        true,
        NoPath,
        false,
        false,
    )),
    requires_explicit_business_session(permission_risk(
        def(
            "close_session_shell",
            ModelVisible,
            TOOL_CATEGORY_JOB,
            Some(PersistentShell),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: JobRun,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(JOB_RUN),
            true,
            NoPath,
            true,
            false,
        ),
        PERMISSION_RISK_JOB,
    )),
    permission_risk(
        def(
            "run_job",
            ModelVisible,
            TOOL_CATEGORY_JOB,
            Some(AsyncJobs),
            TOOL_PROVIDER_AGENT,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Execute,
                risk: JobRun,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(JOB_RUN),
            true,
            NoPath,
            true,
            true,
        ),
        TOOL_CATEGORY_JOB,
    ),
    permission_risk(
        def(
            "stop_job",
            ModelVisible,
            TOOL_CATEGORY_JOB,
            None,
            TOOL_PROVIDER_NATIVE,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: JobRun,
                approval: super::ToolApprovalPolicy::Standard,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(JOB_RUN),
            true,
            NoPath,
            true,
            false,
        ),
        PERMISSION_RISK_JOB,
    ),
    def(
        "job_status",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    def(
        "job_log",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    def(
        "observe_jobs",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
];

pub(super) const LISTING_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "list_jobs",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    def(
        "job_tail",
        ModelHidden,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Observe,
            risk: Read,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::PureRead,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
];
