use super::AgentCapability::{AsyncJobs, Shell};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    def, disabled, permission_risk, ToolDefinition, TOOL_CATEGORY_CODEX, TOOL_CATEGORY_JOB,
};
use crate::tool_runtime::metadata::{
    ToolPathHint::None as NoPath,
    ToolRisk::{JobRun, ReadOnly},
    JOB_RUN, RUNTIME_READ, TOOL_PROVIDER_AGENT, TOOL_PROVIDER_NATIVE,
};
use crate::tool_runtime::RUN_CODEX_DISABLED_MESSAGE;

pub(super) const EXECUTION_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "run_shell",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        Some(Shell),
        TOOL_PROVIDER_AGENT,
        JobRun,
        Some(JOB_RUN),
        true,
        NoPath,
        true,
        true,
    ),
    permission_risk(
        def(
            "run_job",
            ModelVisible,
            TOOL_CATEGORY_JOB,
            Some(AsyncJobs),
            TOOL_PROVIDER_AGENT,
            JobRun,
            Some(JOB_RUN),
            true,
            NoPath,
            true,
            true,
        ),
        TOOL_CATEGORY_JOB,
    ),
    permission_risk(
        def(
            "stop_job",
            ModelVisible,
            TOOL_CATEGORY_JOB,
            None,
            TOOL_PROVIDER_NATIVE,
            JobRun,
            Some(JOB_RUN),
            true,
            NoPath,
            true,
            false,
        ),
        "job",
    ),
    disabled(
        permission_risk(
            def(
                "run_codex",
                ModelHidden,
                TOOL_CATEGORY_CODEX,
                Some(AsyncJobs),
                TOOL_PROVIDER_AGENT,
                JobRun,
                Some(JOB_RUN),
                true,
                NoPath,
                true,
                true,
            ),
            TOOL_CATEGORY_JOB,
        ),
        RUN_CODEX_DISABLED_MESSAGE,
    ),
    def(
        "job_status",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    def(
        "job_log",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
];

pub(super) const LISTING_DEFINITIONS: &[ToolDefinition] = &[
    def(
        "list_jobs",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    def(
        "job_tail",
        ModelVisible,
        TOOL_CATEGORY_JOB,
        None,
        TOOL_PROVIDER_NATIVE,
        ReadOnly,
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
];
