use super::AgentCapability::{GitOrShell, OwnerOnly};
use super::ToolVisibility::{ModelHidden, ModelVisible};
use super::{
    def, extra_accepted_flattened_args, model_spec, requires_explicit_business_session,
    ToolDefinition, TOOL_CATEGORY_SESSION, TOOL_CATEGORY_VALIDATION,
};
use crate::tool_runtime::metadata::{
    ToolPathHint::None as NoPath, ToolRisk::Read, PROJECT_READ, PROJECT_WRITE, RUNTIME_READ,
    SESSION_COLLABORATE, TOOL_PROVIDER_CONTROL,
};
use crate::tool_runtime::registry::input_schemas::{
    close_session_input_schema, complete_session_message_input_schema,
    finish_coding_task_input_schema, get_session_assignment_input_schema,
    list_session_messages_input_schema, observe_session_messages_input_schema,
    post_session_message_input_schema, resolve_session_message_input_schema,
    session_discussion_summary_input_schema, session_handoff_summary_input_schema,
    session_summary_input_schema, update_session_context_input_schema,
    validation_summary_input_schema, work_on_project_input_schema,
};

pub(super) const DEFINITIONS: &[ToolDefinition] = &[
    def(
        "start_session",
        ModelHidden,
        TOOL_CATEGORY_SESSION,
        None,
        TOOL_PROVIDER_CONTROL,
        super::ToolSemanticContract {
            effect: super::ToolEffect::Mutate,
            risk: super::ToolRisk::WorkflowManage,
            approval: super::ToolApprovalPolicy::None,
            idempotency: super::ToolIdempotency::NonIdempotent,
        },
        Some(RUNTIME_READ),
        false,
        NoPath,
        false,
        false,
    ),
    extra_accepted_flattened_args(
        def(
            "start_coding_task",
            ModelHidden,
            "workflow",
            Some(GitOrShell),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::WorkflowManage,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        &["session_id"],
    ),
    model_spec(
        def(
            "work_on_project",
            ModelVisible,
            "workflow",
            Some(GitOrShell),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::WorkflowManage,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(RUNTIME_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Canonical model entry for ordinary coding/review via an existing project or Runner path; Git not required. Supports exact Session continuation and returns compact workflow plus project instructions.",
        work_on_project_input_schema,
    ),
    requires_explicit_business_session(model_spec(
        def(
            "finish_coding_task",
            ModelVisible,
            "workflow",
            Some(GitOrShell),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Return an optional deterministic evidence snapshot for model review, including workspace, validation, jobs, and recorded tool events. The result is advisory: it does not decide task completion, replace direct diff or test review, or generate the user-facing final report.",
        finish_coding_task_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "session_summary",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Return a bounded structured summary from the session ledger for an explicit session_id: recorded events, message-board summary, task mode, guards, and lifecycle. Uses durable ledger data where session persistence is configured.",
        session_summary_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "update_session_context",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(PROJECT_WRITE),
            true,
            NoPath,
            false,
            false,
        ),
        "Update Session defaults. Requires an authorized project matching the exact Session project; cross-project escape is not supported. Context and event commit under the store lock; the background writer persists, so success does not mean disk flush. Never falls back and never creates unknown Sessions.",
        update_session_context_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "close_session",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::DesiredState,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
        ),
        "Explicitly close a workflow session (Active to Closed) for a required session_id. Query remains available; write/shell/mutation tools are denied. Idempotent when already closed; unknown ids fail without create. finish_coding_task does not close.",
        close_session_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "validation_summary",
            ModelVisible,
            TOOL_CATEGORY_VALIDATION,
            Some(OwnerOnly),
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(PROJECT_READ),
            true,
            NoPath,
            false,
            false,
        ),
        "Read bounded structured validation evidence already recorded in an explicit project-scoped session ledger. Does not run Cargo or shell commands, enqueue an agent request, read project files, mutate the workspace, or replace finish_coding_task.",
        validation_summary_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "post_session_message",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
        ),
        "Post a bounded collaboration message (todo, question, progress, guidance, risk, or decision). High-priority guidance may require request-scoped ACK; ACK neither resolves nor gates work. Use complete_session_message to atomically answer and resolve a finished todo.",
        post_session_message_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "list_session_messages",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Read bounded session-local messages with exact filters. For an executable todo, prefer get_session_assignment so the todo, all retained direct replies, and its completion fence come from one store snapshot.",
        list_session_messages_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "get_session_assignment",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Atomically read one exact open todo plus all retained direct replies and return the opaque assignment_fence required by complete_session_message. Unrelated Session traffic and ACK bookkeeping do not stale it; incomplete retained assignment history fails closed.",
        get_session_assignment_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "observe_session_messages",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Observe Session message-state delta after an opaque durable cursor. No token establishes the current baseline and returns no history; token calls may wait once for change. Reports retention loss; never a subscription, delivery receipt, or model-context proof.",
        observe_session_messages_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "resolve_session_message",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::NonIdempotent,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
        ),
        "Mark a session-local ledger message resolved. Idempotent when the message is already resolved; metadata-only and never modifies project files.",
        resolve_session_message_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "complete_session_message",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Mutate,
                risk: super::ToolRisk::SessionCollaborate,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::FencedReplay,
            },
            Some(SESSION_COLLABORATE),
            false,
            NoPath,
            false,
            false,
        ),
        "Atomically answer and resolve one exact open todo. expected_assignment_fence is required and must be the exact opaque fence from get_session_assignment; completion_key separately keeps uncertain-result retries idempotent.",
        complete_session_message_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "session_discussion_summary",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Return a bounded structured aggregate of session-local discussion from the recorded session ledger. Does not call an LLM or generate natural-language summaries.",
        session_discussion_summary_input_schema,
    )),
    requires_explicit_business_session(model_spec(
        def(
            "session_handoff_summary",
            ModelVisible,
            TOOL_CATEGORY_SESSION,
            None,
            TOOL_PROVIDER_CONTROL,
            super::ToolSemanticContract {
                effect: super::ToolEffect::Observe,
                risk: Read,
                approval: super::ToolApprovalPolicy::None,
                idempotency: super::ToolIdempotency::PureRead,
            },
            Some(RUNTIME_READ),
            false,
            NoPath,
            false,
            false,
        ),
        "Read-only handoff for multi-step tasks, explicit session_id. Reads session ledger collaboration and ledger-derived validation. Diagnostics use bounded tails or safe result metadata; validation.parser.available is false if absent. Worker/coordinator read.",
        session_handoff_summary_input_schema,
    )),
];
